export const INVESTMENT_EVENT_TYPES = {
  CONTRIBUTION: 'CONTRIBUTION',
  OPENING_BALANCE: 'OPENING_BALANCE',
  OPENING_INCOME_CREDIT: 'OPENING_INCOME_CREDIT',
  WITHDRAWAL_PRINCIPAL: 'WITHDRAWAL_PRINCIPAL',
} as const;

export type InvestmentEventType =
  (typeof INVESTMENT_EVENT_TYPES)[keyof typeof INVESTMENT_EVENT_TYPES];

export const KNOWN_INVESTMENT_EVENT_TYPES: readonly InvestmentEventType[] = Object.freeze(
  Object.values(INVESTMENT_EVENT_TYPES),
);

export const OPENING_INVESTMENT_EVENT_TYPES: readonly InvestmentEventType[] = Object.freeze([
  INVESTMENT_EVENT_TYPES.OPENING_BALANCE,
  INVESTMENT_EVENT_TYPES.OPENING_INCOME_CREDIT,
]);

export const INCOME_INVESTMENT_EVENT_TYPES: readonly InvestmentEventType[] = Object.freeze([
  INVESTMENT_EVENT_TYPES.OPENING_INCOME_CREDIT,
]);