import { MOCK_SEED_DATE } from './shared';
import type { FinancialAccountRecord } from './types';

export const mockFinancialAccountsData: FinancialAccountRecord[] = [
  {
    id: 1,
    userId: 1,
    name: 'hdfc-salary',
    displayName: 'HDFC Salary Account',
    accountType: 'bank',
    institutionName: 'HDFC Bank',
    accountNumberMasked: 'XXXX1122',
    currency: 'INR',
    isActive: true,
    createdAt: MOCK_SEED_DATE,
    updatedAt: MOCK_SEED_DATE,
  },
  {
    id: 2,
    userId: 1,
    name: 'icici-savings',
    displayName: 'ICICI Savings Account',
    accountType: 'bank',
    institutionName: 'ICICI Bank',
    accountNumberMasked: 'XXXX2211',
    currency: 'INR',
    isActive: true,
    createdAt: MOCK_SEED_DATE,
    updatedAt: MOCK_SEED_DATE,
  },
  {
    id: 3,
    userId: 1,
    name: 'axis-savings',
    displayName: 'Axis Savings Account',
    accountType: 'bank',
    institutionName: 'Axis Bank',
    accountNumberMasked: 'XXXX3344',
    currency: 'INR',
    isActive: true,
    createdAt: MOCK_SEED_DATE,
    updatedAt: MOCK_SEED_DATE,
  },
  {
    id: 4,
    userId: 1,
    name: 'sbi-reserve',
    displayName: 'SBI Reserve Account',
    accountType: 'bank',
    institutionName: 'State Bank of India',
    accountNumberMasked: 'XXXX7788',
    currency: 'INR',
    isActive: true,
    createdAt: MOCK_SEED_DATE,
    updatedAt: MOCK_SEED_DATE,
  },
  {
    id: 5,
    userId: 1,
    name: 'wallet-upi',
    displayName: 'UPI Wallet',
    accountType: 'wallet',
    institutionName: 'UPI Wallet',
    accountNumberMasked: null,
    currency: 'INR',
    isActive: true,
    createdAt: MOCK_SEED_DATE,
    updatedAt: MOCK_SEED_DATE,
  },
];