import { dateFromBaseDate } from './shared';
import type { GoalRecord } from './types';

const baseDate = new Date();

export const mockGoalsData: GoalRecord[] = [
  {
    id: 1,
    name: 'Emergency Fund',
    categoryId: 18,
    categoryLabelSnapshot: 'Personal',
    description: 'Savings buffer for emergencies and unexpected expenses.',
    icon: 'medical',
    targetAmount: 10000,
    currentAmount: 6500,
    startDate: dateFromBaseDate(baseDate, -150),
    deadline: dateFromBaseDate(baseDate, 120),
    userId: 1,
    createdAt: dateFromBaseDate(baseDate, -150),
    updatedAt: dateFromBaseDate(baseDate, -2),
  },
  {
    id: 2,
    name: 'Vacation to Japan',
    categoryId: 19,
    categoryLabelSnapshot: 'Travel',
    description: 'Trip fund for flights, stays, and local travel.',
    icon: 'car',
    targetAmount: 5000,
    currentAmount: 1250,
    startDate: dateFromBaseDate(baseDate, -100),
    deadline: dateFromBaseDate(baseDate, 180),
    userId: 1,
    createdAt: dateFromBaseDate(baseDate, -100),
    updatedAt: dateFromBaseDate(baseDate, -4),
  },
  {
    id: 3,
    name: 'New Laptop',
    categoryId: 18,
    categoryLabelSnapshot: 'Personal',
    description: 'Save for a replacement laptop for work and study.',
    icon: 'book',
    targetAmount: 2000,
    currentAmount: 0,
    startDate: dateFromBaseDate(baseDate, -35),
    deadline: dateFromBaseDate(baseDate, 75),
    userId: 1,
    createdAt: dateFromBaseDate(baseDate, -35),
    updatedAt: dateFromBaseDate(baseDate, -1),
  },
  {
    id: 4,
    name: 'Home Down Payment',
    categoryId: 20,
    categoryLabelSnapshot: 'Housing',
    description: 'Dedicated savings goal for a home down payment.',
    icon: 'home',
    targetAmount: 7500,
    currentAmount: 7500,
    startDate: dateFromBaseDate(baseDate, -220),
    deadline: dateFromBaseDate(baseDate, 240),
    userId: 1,
    createdAt: dateFromBaseDate(baseDate, -220),
    updatedAt: dateFromBaseDate(baseDate, -1),
  },
  {
    id: 5,
    name: 'Bike Upgrade',
    categoryId: 21,
    categoryLabelSnapshot: 'Lifestyle',
    description: 'Upgrade to a better commuter bike this week.',
    icon: 'bike',
    targetAmount: 3000,
    currentAmount: 900,
    startDate: dateFromBaseDate(baseDate, -45),
    deadline: dateFromBaseDate(baseDate, 4),
    userId: 1,
    createdAt: dateFromBaseDate(baseDate, -45),
    updatedAt: dateFromBaseDate(baseDate, -2),
  },
  {
    id: 6,
    name: 'Medical Buffer',
    categoryId: 22,
    categoryLabelSnapshot: 'Health',
    description: 'Emergency reserve for medical visits and prescriptions.',
    icon: 'medical',
    targetAmount: 4000,
    currentAmount: 1200,
    startDate: dateFromBaseDate(baseDate, -80),
    deadline: dateFromBaseDate(baseDate, -10),
    userId: 1,
    createdAt: dateFromBaseDate(baseDate, -80),
    updatedAt: dateFromBaseDate(baseDate, -3),
  },
];

export const mockGoalsStore = [...mockGoalsData];
