import { dateFromBaseDate } from './shared';
import type { InvestmentEventRecord } from './types';

const baseDate = new Date();

export const mockInvestmentEventsData: InvestmentEventRecord[] = [
  {
    id: 1,
    investmentId: 1,
    recurringPlanId: 1,
    sourceAccountId: 1,
    linkedTransactionId: null,
    eventType: 'contribution',
    dueDate: dateFromBaseDate(baseDate, -35),
    status: 'CONFIRMED',
    eventSource: 'RECURRING_PLAN',
    sequenceNumber: 11,
    eventDate: dateFromBaseDate(baseDate, -35),
    amount: 12000,
    units: 145.23,
    pricePerUnit: 82.63,
    netAmount: 12000,
    notes: 'Monthly SIP contribution',
    meta: { frequency: 'monthly' },
    createdAt: dateFromBaseDate(baseDate, -35),
    updatedAt: dateFromBaseDate(baseDate, -35),
  },
  {
    id: 2,
    investmentId: 6,
    recurringPlanId: 4,
    sourceAccountId: 2,
    linkedTransactionId: null,
    eventType: 'deposit',
    dueDate: dateFromBaseDate(baseDate, -30),
    status: 'CONFIRMED',
    eventSource: 'RECURRING_PLAN',
    sequenceNumber: 8,
    eventDate: dateFromBaseDate(baseDate, -30),
    amount: 9000,
    units: null,
    pricePerUnit: null,
    netAmount: 9000,
    notes: 'Recurring deposit installment',
    meta: { recurrence: 'monthly' },
    createdAt: dateFromBaseDate(baseDate, -30),
    updatedAt: dateFromBaseDate(baseDate, -30),
  },
  {
    id: 3,
    investmentId: 5,
    recurringPlanId: 3,
    sourceAccountId: 1,
    linkedTransactionId: null,
    eventType: 'premium',
    dueDate: dateFromBaseDate(baseDate, -15),
    status: 'CONFIRMED',
    eventSource: 'RECURRING_PLAN',
    sequenceNumber: 10,
    eventDate: dateFromBaseDate(baseDate, -15),
    amount: 6000,
    units: null,
    pricePerUnit: null,
    netAmount: 6000,
    notes: 'LIC premium payment',
    meta: { cadenceUnit: 'month', cadenceInterval: 1 },
    createdAt: dateFromBaseDate(baseDate, -15),
    updatedAt: dateFromBaseDate(baseDate, -15),
  },
];