import { MOCK_SEED_DATE } from './shared';
import { InvestmentAssetTaxonomyRecord } from './types';

const now = MOCK_SEED_DATE;

export const mockInvestmentAssetTaxonomyData: InvestmentAssetTaxonomyRecord[] = [
  {
    id: 1,
    label: 'Market',
    nodeType: 'category',
    level: 1,
    parentId: null,
    sortOrder: 1,
    isActive: true,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 2,
    label: 'Deposits',
    nodeType: 'category',
    level: 1,
    parentId: null,
    sortOrder: 2,
    isActive: true,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 3,
    label: 'Retirement',
    nodeType: 'category',
    level: 1,
    parentId: null,
    sortOrder: 3,
    isActive: true,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 4,
    label: 'Insurance',
    nodeType: 'category',
    level: 1,
    parentId: null,
    sortOrder: 4,
    isActive: true,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 5,
    label: 'Metals',
    nodeType: 'category',
    level: 1,
    parentId: null,
    sortOrder: 5,
    isActive: true,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 11,
    label: 'Mutual Fund',
    nodeType: 'type',
    level: 2,
    parentId: 1,
    sortOrder: 1,
    isActive: true,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 12,
    label: 'Stocks',
    nodeType: 'type',
    level: 2,
    parentId: 1,
    sortOrder: 2,
    isActive: true,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 13,
    label: 'Fixed Deposit',
    nodeType: 'type',
    level: 2,
    parentId: 2,
    sortOrder: 1,
    isActive: true,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 17,
    label: 'Recurring Deposit',
    nodeType: 'type',
    level: 2,
    parentId: 2,
    sortOrder: 2,
    isActive: true,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 14,
    label: 'PPF',
    nodeType: 'type',
    level: 2,
    parentId: 3,
    sortOrder: 1,
    isActive: true,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 15,
    label: 'LIC',
    nodeType: 'type',
    level: 2,
    parentId: 4,
    sortOrder: 1,
    isActive: true,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 16,
    label: 'Gold',
    nodeType: 'type',
    level: 2,
    parentId: 5,
    sortOrder: 1,
    isActive: true,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 21,
    label: 'Equity',
    nodeType: 'subtype',
    level: 3,
    parentId: 11,
    sortOrder: 1,
    isActive: true,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 22,
    label: 'Debt',
    nodeType: 'subtype',
    level: 3,
    parentId: 11,
    sortOrder: 2,
    isActive: true,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 23,
    label: 'Large Cap',
    nodeType: 'segment',
    level: 4,
    parentId: 21,
    sortOrder: 1,
    isActive: true,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 24,
    label: 'Index Fund',
    nodeType: 'segment',
    level: 4,
    parentId: 21,
    sortOrder: 2,
    isActive: true,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 25,
    label: 'Liquid',
    nodeType: 'segment',
    level: 4,
    parentId: 22,
    sortOrder: 1,
    isActive: true,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 26,
    label: 'Bluechip Index',
    nodeType: 'detail',
    level: 5,
    parentId: 24,
    sortOrder: 1,
    isActive: true,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 27,
    label: 'Domestic',
    nodeType: 'subtype',
    level: 3,
    parentId: 12,
    sortOrder: 1,
    isActive: true,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 28,
    label: 'International',
    nodeType: 'subtype',
    level: 3,
    parentId: 12,
    sortOrder: 2,
    isActive: true,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 29,
    label: 'Banking',
    nodeType: 'segment',
    level: 4,
    parentId: 27,
    sortOrder: 1,
    isActive: true,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 30,
    label: 'Technology',
    nodeType: 'segment',
    level: 4,
    parentId: 27,
    sortOrder: 2,
    isActive: true,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 31,
    label: 'Short Term',
    nodeType: 'subtype',
    level: 3,
    parentId: 13,
    sortOrder: 1,
    isActive: true,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 32,
    label: 'Long Term',
    nodeType: 'subtype',
    level: 3,
    parentId: 13,
    sortOrder: 2,
    isActive: true,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 33,
    label: 'Monthly Deposit',
    nodeType: 'subtype',
    level: 3,
    parentId: 17,
    sortOrder: 1,
    isActive: true,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 34,
    label: 'Tax Saver',
    nodeType: 'subtype',
    level: 3,
    parentId: 14,
    sortOrder: 1,
    isActive: true,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 35,
    label: 'Traditional',
    nodeType: 'subtype',
    level: 3,
    parentId: 15,
    sortOrder: 1,
    isActive: true,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 36,
    label: 'Term Plan',
    nodeType: 'subtype',
    level: 3,
    parentId: 15,
    sortOrder: 2,
    isActive: true,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 37,
    label: 'Online Policy',
    nodeType: 'segment',
    level: 4,
    parentId: 36,
    sortOrder: 1,
    isActive: true,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 38,
    label: 'Physical',
    nodeType: 'subtype',
    level: 3,
    parentId: 16,
    sortOrder: 1,
    isActive: true,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 39,
    label: 'Digital',
    nodeType: 'subtype',
    level: 3,
    parentId: 16,
    sortOrder: 2,
    isActive: true,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 40,
    label: 'Coins',
    nodeType: 'segment',
    level: 4,
    parentId: 38,
    sortOrder: 1,
    isActive: true,
    createdAt: now,
    updatedAt: now,
  },
];