import { dateFromBaseDate } from './shared';
import type { MockInvestment } from './types';

const baseDate = new Date();

export const mockInvestmentsData: MockInvestment[] = [
  {
    id: 1,
    userId: 1,
    accountId: 1,
    assetTaxonomyId: 11,
    name: 'Axis Bluechip SIP',
    assetType: 'Mutual Fund',
    assetCategory: 'market',
    holdingMode: 'demat',
    institutionName: 'Axis AMC',
    referenceNumber: 'Folio 1182-AXIS-991',
    status: 'active',
    startDate: dateFromBaseDate(baseDate, -1184),
    maturityDate: null,
    currency: 'INR',
    totalInvested: 420000,
    currentValue: 458000,
    currentValueSource: 'manual',
    lastValuationAt: dateFromBaseDate(baseDate, -2),
    insuranceCover: 0,
    documentsMeta: { documents: ['CAS statement', 'nominee confirmation'] },
    notes: 'Long-term wealth compounding bucket',
    createdAt: dateFromBaseDate(baseDate, -8),
    updatedAt: dateFromBaseDate(baseDate, -8),
  },
  {
    id: 2,
    userId: 1,
    accountId: 2,
    assetTaxonomyId: 12,
    name: 'HDFC Bank Shares',
    assetType: 'Stocks',
    assetCategory: 'market',
    holdingMode: 'demat',
    institutionName: 'Zerodha',
    referenceNumber: 'DEM-4511-HDFC',
    status: 'active',
    startDate: dateFromBaseDate(baseDate, -537),
    maturityDate: null,
    currency: 'INR',
    totalInvested: 275000,
    currentValue: 301000,
    currentValueSource: 'manual',
    lastValuationAt: dateFromBaseDate(baseDate, -3),
    insuranceCover: 0,
    documentsMeta: { documents: ['Contract note', 'demat statement'] },
    notes: 'Core banking exposure',
    createdAt: dateFromBaseDate(baseDate, -15),
    updatedAt: dateFromBaseDate(baseDate, -15),
  },
  {
    id: 3,
    userId: 1,
    accountId: 4,
    assetTaxonomyId: 13,
    name: 'SBI Flexi FD',
    assetType: 'Fixed Deposit',
    assetCategory: 'deposits',
    holdingMode: 'self',
    institutionName: 'SBI',
    referenceNumber: 'FD-7741-SBI',
    status: 'active',
    startDate: dateFromBaseDate(baseDate, -550),
    maturityDate: dateFromBaseDate(baseDate, 27),
    currency: 'INR',
    totalInvested: 520000,
    currentValue: 548500,
    currentValueSource: 'manual',
    lastValuationAt: dateFromBaseDate(baseDate, -5),
    insuranceCover: 0,
    documentsMeta: { documents: ['FD receipt'] },
    notes: 'Emergency buffer maturing next month',
    createdAt: dateFromBaseDate(baseDate, -25),
    updatedAt: dateFromBaseDate(baseDate, -25),
  },
  {
    id: 4,
    userId: 1,
    accountId: 4,
    assetTaxonomyId: 14,
    name: 'PPF Account',
    assetType: 'PPF',
    assetCategory: 'retirement',
    holdingMode: 'self',
    institutionName: 'Indian Post',
    referenceNumber: 'PPF-POST-119',
    status: 'active',
    startDate: dateFromBaseDate(baseDate, -2287),
    maturityDate: dateFromBaseDate(baseDate, 3190),
    currency: 'INR',
    totalInvested: 980000,
    currentValue: 1120000,
    currentValueSource: 'manual',
    lastValuationAt: dateFromBaseDate(baseDate, -7),
    insuranceCover: 0,
    documentsMeta: { documents: ['Passbook scan'] },
    notes: 'Retirement-safe debt allocation',
    createdAt: dateFromBaseDate(baseDate, -48),
    updatedAt: dateFromBaseDate(baseDate, -48),
  },
  {
    id: 5,
    userId: 1,
    accountId: 1,
    assetTaxonomyId: 15,
    name: 'LIC Jeevan Anand',
    assetType: 'LIC',
    assetCategory: 'insurance',
    holdingMode: 'self',
    institutionName: 'LIC India',
    referenceNumber: 'POL-9811-LIC',
    status: 'active',
    startDate: dateFromBaseDate(baseDate, -1606),
    maturityDate: dateFromBaseDate(baseDate, 5699),
    currency: 'INR',
    totalInvested: 360000,
    currentValue: 360000,
    currentValueSource: 'policy_statement',
    lastValuationAt: dateFromBaseDate(baseDate, -1),
    insuranceCover: 7500000,
    documentsMeta: { documents: ['Policy bond', 'ECS form'] },
    notes: 'Family protection and maturity corpus',
    createdAt: dateFromBaseDate(baseDate, -10),
    updatedAt: dateFromBaseDate(baseDate, -10),
  },
  {
    id: 6,
    userId: 1,
    accountId: 2,
    assetTaxonomyId: 17,
    name: 'ICICI RD',
    assetType: 'Recurring Deposit',
    assetCategory: 'deposits',
    holdingMode: 'self',
    institutionName: 'ICICI Bank',
    referenceNumber: 'RD-ICICI-715',
    status: 'active',
    startDate: dateFromBaseDate(baseDate, -273),
    maturityDate: dateFromBaseDate(baseDate, 457),
    currency: 'INR',
    totalInvested: 108000,
    currentValue: 114400,
    currentValueSource: 'manual',
    lastValuationAt: dateFromBaseDate(baseDate, -4),
    insuranceCover: 0,
    documentsMeta: { documents: ['RD schedule'] },
    notes: 'Short-term travel fund',
    createdAt: dateFromBaseDate(baseDate, -5),
    updatedAt: dateFromBaseDate(baseDate, -5),
  },
  {
    id: 7,
    userId: 1,
    accountId: null,
    assetTaxonomyId: 16,
    name: 'Physical Gold Coins',
    assetType: 'Gold',
    assetCategory: 'metals',
    holdingMode: 'physical',
    institutionName: 'Tanishq',
    referenceNumber: 'INV-GOLD-2301',
    status: 'active',
    startDate: dateFromBaseDate(baseDate, -603),
    maturityDate: null,
    currency: 'INR',
    totalInvested: 195000,
    currentValue: 213000,
    currentValueSource: 'manual',
    lastValuationAt: dateFromBaseDate(baseDate, -6),
    insuranceCover: 0,
    documentsMeta: { documents: ['Invoice copies'] },
    notes: 'Inflation hedge allocation',
    createdAt: dateFromBaseDate(baseDate, -74),
    updatedAt: dateFromBaseDate(baseDate, -74),
  },
];