import { dateFromBaseDate } from './shared';
import type { MockInvestmentContributionPlan } from './types';

const baseDate = new Date();

export const mockInvestmentContributionPlansData: MockInvestmentContributionPlan[] = [
  {
    id: 1,
    investmentId: 1,
    sourceAccountId: 1,
    status: 'active',
    amount: 12000,
    cadenceUnit: 'month',
    cadenceInterval: 1,
    anchorDate: dateFromBaseDate(baseDate, -365),
    nextDueDate: dateFromBaseDate(baseDate, -5),
    endDate: null,
    reminderDaysBefore: 3,
    autoCreateEvent: false,
    notes: 'Primary equity SIP plan',
    createdAt: dateFromBaseDate(baseDate, -365),
    updatedAt: dateFromBaseDate(baseDate, -40),
  },
  {
    id: 2,
    investmentId: 4,
    sourceAccountId: 4,
    status: 'active',
    amount: 12500,
    cadenceUnit: 'year',
    cadenceInterval: 1,
    anchorDate: dateFromBaseDate(baseDate, -700),
    nextDueDate: dateFromBaseDate(baseDate, 40),
    endDate: null,
    reminderDaysBefore: 15,
    autoCreateEvent: false,
    notes: 'Annual PPF contribution reminder',
    createdAt: dateFromBaseDate(baseDate, -700),
    updatedAt: dateFromBaseDate(baseDate, -60),
  },
  {
    id: 3,
    investmentId: 5,
    sourceAccountId: 1,
    status: 'active',
    amount: 6000,
    cadenceUnit: 'month',
    cadenceInterval: 1,
    anchorDate: dateFromBaseDate(baseDate, -320),
    nextDueDate: dateFromBaseDate(baseDate, 15),
    endDate: null,
    reminderDaysBefore: 5,
    autoCreateEvent: false,
    notes: 'Insurance premium reminder',
    createdAt: dateFromBaseDate(baseDate, -320),
    updatedAt: dateFromBaseDate(baseDate, -15),
  },
  {
    id: 4,
    investmentId: 6,
    sourceAccountId: 2,
    status: 'active',
    amount: 9000,
    cadenceUnit: 'month',
    cadenceInterval: 1,
    anchorDate: dateFromBaseDate(baseDate, -280),
    nextDueDate: dateFromBaseDate(baseDate, 1),
    endDate: dateFromBaseDate(baseDate, 457),
    reminderDaysBefore: 2,
    autoCreateEvent: false,
    notes: 'Recurring deposit installment plan',
    createdAt: dateFromBaseDate(baseDate, -280),
    updatedAt: dateFromBaseDate(baseDate, -30),
  },
];