import { dateFromBaseDate } from './shared';
import type { TransactionRecord } from './types';

const baseDate = new Date();

export const mockTransactionsData: TransactionRecord[] = [
  {
    id: 1,
    userId: 1,
    categoryId: 2,
    goalId: null,
    sourceAccountId: 1,
    destinationAccountId: null,
    linkedInvestmentEventId: null,
    type: 'income',
    transactionKind: 'credit',
    amount: 72000,
    categoryLabelSnapshot: 'Salary',
    date: dateFromBaseDate(baseDate, -30),
    notes: 'Monthly salary credit',
    createdAt: dateFromBaseDate(baseDate, -30),
    updatedAt: dateFromBaseDate(baseDate, -30),
  },
  {
    id: 2,
    userId: 1,
    categoryId: 8,
    goalId: null,
    sourceAccountId: 1,
    destinationAccountId: null,
    linkedInvestmentEventId: null,
    type: 'expense',
    transactionKind: 'debit',
    amount: 18500,
    categoryLabelSnapshot: 'Rent',
    date: dateFromBaseDate(baseDate, -29),
    notes: 'Monthly apartment rent',
    createdAt: dateFromBaseDate(baseDate, -29),
    updatedAt: dateFromBaseDate(baseDate, -29),
  },
  {
    id: 3,
    userId: 1,
    categoryId: 1,
    goalId: null,
    sourceAccountId: 1,
    destinationAccountId: null,
    linkedInvestmentEventId: null,
    type: 'expense',
    transactionKind: 'debit',
    amount: 3260,
    categoryLabelSnapshot: 'Groceries',
    date: dateFromBaseDate(baseDate, -27),
    notes: 'Weekly grocery run',
    createdAt: dateFromBaseDate(baseDate, -27),
    updatedAt: dateFromBaseDate(baseDate, -27),
  },
  {
    id: 4,
    userId: 1,
    categoryId: 5,
    goalId: null,
    sourceAccountId: 1,
    destinationAccountId: null,
    linkedInvestmentEventId: null,
    type: 'expense',
    transactionKind: 'debit',
    amount: 2480,
    categoryLabelSnapshot: 'Utilities',
    date: dateFromBaseDate(baseDate, -26),
    notes: 'Electricity and water bill',
    createdAt: dateFromBaseDate(baseDate, -26),
    updatedAt: dateFromBaseDate(baseDate, -26),
  },
  {
    id: 5,
    userId: 1,
    categoryId: 6,
    goalId: null,
    sourceAccountId: 2,
    destinationAccountId: null,
    linkedInvestmentEventId: null,
    type: 'income',
    transactionKind: 'credit',
    amount: 14500,
    categoryLabelSnapshot: 'Freelance',
    date: dateFromBaseDate(baseDate, -24),
    notes: 'Freelance design payout',
    createdAt: dateFromBaseDate(baseDate, -24),
    updatedAt: dateFromBaseDate(baseDate, -24),
  },
  {
    id: 6,
    userId: 1,
    categoryId: 7,
    goalId: null,
    sourceAccountId: 5,
    destinationAccountId: null,
    linkedInvestmentEventId: null,
    type: 'expense',
    transactionKind: 'debit',
    amount: 1760,
    categoryLabelSnapshot: 'Dining',
    date: dateFromBaseDate(baseDate, -22),
    notes: 'Weekend dining with family',
    createdAt: dateFromBaseDate(baseDate, -22),
    updatedAt: dateFromBaseDate(baseDate, -22),
  },
  {
    id: 7,
    userId: 1,
    categoryId: 3,
    goalId: null,
    sourceAccountId: 5,
    destinationAccountId: null,
    linkedInvestmentEventId: null,
    type: 'expense',
    transactionKind: 'debit',
    amount: 920,
    categoryLabelSnapshot: 'Transportation',
    date: dateFromBaseDate(baseDate, -20),
    notes: 'Metro and cab charges',
    createdAt: dateFromBaseDate(baseDate, -20),
    updatedAt: dateFromBaseDate(baseDate, -20),
  },
  {
    id: 8,
    userId: 1,
    categoryId: 9,
    goalId: null,
    sourceAccountId: 1,
    destinationAccountId: null,
    linkedInvestmentEventId: null,
    type: 'expense',
    transactionKind: 'debit',
    amount: 899,
    categoryLabelSnapshot: 'Internet',
    date: dateFromBaseDate(baseDate, -19),
    notes: 'Fiber broadband renewal',
    createdAt: dateFromBaseDate(baseDate, -19),
    updatedAt: dateFromBaseDate(baseDate, -19),
  },
  {
    id: 9,
    userId: 1,
    categoryId: 10,
    goalId: null,
    sourceAccountId: 2,
    destinationAccountId: null,
    linkedInvestmentEventId: null,
    type: 'expense',
    transactionKind: 'debit',
    amount: 2200,
    categoryLabelSnapshot: 'Healthcare',
    date: dateFromBaseDate(baseDate, -16),
    notes: 'Clinic consultation and medicines',
    createdAt: dateFromBaseDate(baseDate, -16),
    updatedAt: dateFromBaseDate(baseDate, -16),
  },
  {
    id: 10,
    userId: 1,
    categoryId: 11,
    goalId: null,
    sourceAccountId: 2,
    destinationAccountId: null,
    linkedInvestmentEventId: null,
    type: 'expense',
    transactionKind: 'debit',
    amount: 1500,
    categoryLabelSnapshot: 'Education',
    date: dateFromBaseDate(baseDate, -14),
    notes: 'Online course subscription',
    createdAt: dateFromBaseDate(baseDate, -14),
    updatedAt: dateFromBaseDate(baseDate, -14),
  },
  {
    id: 11,
    userId: 1,
    categoryId: 12,
    goalId: null,
    sourceAccountId: 5,
    destinationAccountId: null,
    linkedInvestmentEventId: null,
    type: 'expense',
    transactionKind: 'debit',
    amount: 1200,
    categoryLabelSnapshot: 'Gifts',
    date: dateFromBaseDate(baseDate, -10),
    notes: 'Birthday gift purchase',
    createdAt: dateFromBaseDate(baseDate, -10),
    updatedAt: dateFromBaseDate(baseDate, -10),
  },
  {
    id: 12,
    userId: 1,
    categoryId: 4,
    goalId: null,
    sourceAccountId: 5,
    destinationAccountId: null,
    linkedInvestmentEventId: null,
    type: 'expense',
    transactionKind: 'debit',
    amount: 2100,
    categoryLabelSnapshot: 'Entertainment',
    date: dateFromBaseDate(baseDate, -8),
    notes: 'Movie and streaming recharge',
    createdAt: dateFromBaseDate(baseDate, -8),
    updatedAt: dateFromBaseDate(baseDate, -8),
  },
  {
    id: 13,
    userId: 1,
    categoryId: 15,
    goalId: 4,
    sourceAccountId: 3,
    destinationAccountId: null,
    linkedInvestmentEventId: null,
    type: 'income',
    transactionKind: 'goal_contribution',
    amount: 3000,
    categoryLabelSnapshot: 'Home Savings',
    date: dateFromBaseDate(baseDate, -180),
    notes: 'Milestone contribution for Home Down Payment',
    createdAt: dateFromBaseDate(baseDate, -180),
    updatedAt: dateFromBaseDate(baseDate, -180),
  },
  {
    id: 14,
    userId: 1,
    categoryId: 13,
    goalId: 1,
    sourceAccountId: 1,
    destinationAccountId: null,
    linkedInvestmentEventId: null,
    type: 'income',
    transactionKind: 'goal_contribution',
    amount: 4000,
    categoryLabelSnapshot: 'Savings',
    date: dateFromBaseDate(baseDate, -120),
    notes: 'Initial contribution for Emergency Fund',
    createdAt: dateFromBaseDate(baseDate, -120),
    updatedAt: dateFromBaseDate(baseDate, -120),
  },
  {
    id: 15,
    userId: 1,
    categoryId: 14,
    goalId: 2,
    sourceAccountId: 2,
    destinationAccountId: null,
    linkedInvestmentEventId: null,
    type: 'income',
    transactionKind: 'goal_contribution',
    amount: 1250,
    categoryLabelSnapshot: 'Travel Fund',
    date: dateFromBaseDate(baseDate, -60),
    notes: 'Contribution for Vacation to Japan',
    createdAt: dateFromBaseDate(baseDate, -60),
    updatedAt: dateFromBaseDate(baseDate, -60),
  },
  {
    id: 16,
    userId: 1,
    categoryId: 13,
    goalId: 1,
    sourceAccountId: 1,
    destinationAccountId: null,
    linkedInvestmentEventId: null,
    type: 'income',
    transactionKind: 'goal_contribution',
    amount: 2500,
    categoryLabelSnapshot: 'Savings',
    date: dateFromBaseDate(baseDate, -40),
    notes: 'Top-up contribution for Emergency Fund',
    createdAt: dateFromBaseDate(baseDate, -40),
    updatedAt: dateFromBaseDate(baseDate, -40),
  },
  {
    id: 17,
    userId: 1,
    categoryId: 17,
    goalId: 6,
    sourceAccountId: 4,
    destinationAccountId: null,
    linkedInvestmentEventId: null,
    type: 'income',
    transactionKind: 'goal_contribution',
    amount: 1200,
    categoryLabelSnapshot: 'Health Reserve',
    date: dateFromBaseDate(baseDate, -30),
    notes: 'Contribution for Medical Buffer',
    createdAt: dateFromBaseDate(baseDate, -30),
    updatedAt: dateFromBaseDate(baseDate, -30),
  },
  {
    id: 18,
    userId: 1,
    categoryId: 15,
    goalId: 4,
    sourceAccountId: 3,
    destinationAccountId: null,
    linkedInvestmentEventId: null,
    type: 'income',
    transactionKind: 'goal_contribution',
    amount: 4500,
    categoryLabelSnapshot: 'Home Savings',
    date: dateFromBaseDate(baseDate, -20),
    notes: 'Final contribution for Home Down Payment',
    createdAt: dateFromBaseDate(baseDate, -20),
    updatedAt: dateFromBaseDate(baseDate, -20),
  },
  {
    id: 19,
    userId: 1,
    categoryId: 16,
    goalId: 5,
    sourceAccountId: 5,
    destinationAccountId: null,
    linkedInvestmentEventId: null,
    type: 'income',
    transactionKind: 'goal_contribution',
    amount: 900,
    categoryLabelSnapshot: 'Transport Upgrade',
    date: dateFromBaseDate(baseDate, -12),
    notes: 'Contribution for Bike Upgrade',
    createdAt: dateFromBaseDate(baseDate, -12),
    updatedAt: dateFromBaseDate(baseDate, -12),
  },
  {
    id: 20,
    userId: 1,
    categoryId: 13,
    goalId: null,
    sourceAccountId: 1,
    destinationAccountId: null,
    linkedInvestmentEventId: 1,
    type: 'expense',
    transactionKind: 'investment_contribution',
    amount: 12000,
    categoryLabelSnapshot: 'Savings',
    date: dateFromBaseDate(baseDate, -35),
    notes: 'Axis Bluechip SIP debit',
    createdAt: dateFromBaseDate(baseDate, -35),
    updatedAt: dateFromBaseDate(baseDate, -35),
  },
  {
    id: 21,
    userId: 1,
    categoryId: 13,
    goalId: null,
    sourceAccountId: 2,
    destinationAccountId: null,
    linkedInvestmentEventId: 2,
    type: 'expense',
    transactionKind: 'investment_contribution',
    amount: 9000,
    categoryLabelSnapshot: 'Savings',
    date: dateFromBaseDate(baseDate, -30),
    notes: 'ICICI RD installment debit',
    createdAt: dateFromBaseDate(baseDate, -30),
    updatedAt: dateFromBaseDate(baseDate, -30),
  },
  {
    id: 22,
    userId: 1,
    categoryId: 17,
    goalId: null,
    sourceAccountId: 1,
    destinationAccountId: null,
    linkedInvestmentEventId: 3,
    type: 'expense',
    transactionKind: 'investment_contribution',
    amount: 6000,
    categoryLabelSnapshot: 'Health Reserve',
    date: dateFromBaseDate(baseDate, -15),
    notes: 'LIC premium debit',
    createdAt: dateFromBaseDate(baseDate, -15),
    updatedAt: dateFromBaseDate(baseDate, -15),
  },
];
