-- Alters an existing database to align with server/prisma/schema.prisma
-- Safe to run on local Postgres after initial bootstrap.

BEGIN;

-- 1) Drop circular FKs temporarily for type/constraint realignment.
ALTER TABLE IF EXISTS public.transactions
  DROP CONSTRAINT IF EXISTS "transactions_linkedInvestmentEventId_fkey";
ALTER TABLE IF EXISTS public.investment_events
  DROP CONSTRAINT IF EXISTS "investment_events_linkedTransactionId_fkey";

-- 2) Ensure ID columns are identity-backed autoincrement where Prisma expects it.
DO $$
BEGIN
  IF EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_schema='public' AND table_name='users' AND column_name='id' AND is_identity='NO'
  ) THEN
    ALTER TABLE public.users ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY;
  END IF;
END $$;

DO $$
BEGIN
  IF EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_schema='public' AND table_name='categories' AND column_name='id' AND is_identity='NO'
  ) THEN
    ALTER TABLE public.categories ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY;
  END IF;
END $$;

DO $$
BEGIN
  IF EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_schema='public' AND table_name='financial_accounts' AND column_name='id' AND is_identity='NO'
  ) THEN
    ALTER TABLE public.financial_accounts ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY;
  END IF;
END $$;

DO $$
BEGIN
  IF EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_schema='public' AND table_name='goals' AND column_name='id' AND is_identity='NO'
  ) THEN
    ALTER TABLE public.goals ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY;
  END IF;
END $$;

DO $$
BEGIN
  IF EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_schema='public' AND table_name='investments' AND column_name='id' AND is_identity='NO'
  ) THEN
    ALTER TABLE public.investments ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY;
  END IF;
END $$;

DO $$
BEGIN
  IF EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_schema='public' AND table_name='investment_asset_taxonomy' AND column_name='id' AND is_identity='NO'
  ) THEN
    ALTER TABLE public.investment_asset_taxonomy ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY;
  END IF;
END $$;

DO $$
BEGIN
  IF EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_schema='public' AND table_name='investment_events' AND column_name='id' AND is_identity='NO'
  ) THEN
    ALTER TABLE public.investment_events ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY;
  END IF;
END $$;

DO $$
BEGIN
  IF EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_schema='public' AND table_name='investment_contribution_plans' AND column_name='id' AND is_identity='NO'
  ) THEN
    ALTER TABLE public.investment_contribution_plans ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY;
  END IF;
END $$;

DO $$
BEGIN
  IF EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_schema='public' AND table_name='valuation_snapshots' AND column_name='id' AND is_identity='NO'
  ) THEN
    ALTER TABLE public.valuation_snapshots ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY;
  END IF;
END $$;

-- transactions.id and linked transaction refs are integer in canonical model.
ALTER TABLE IF EXISTS public.investment_events
  ALTER COLUMN "linkedTransactionId" TYPE INTEGER USING "linkedTransactionId"::INTEGER;
ALTER TABLE IF EXISTS public.transactions
  ALTER COLUMN "id" TYPE INTEGER USING "id"::INTEGER;

DO $$
BEGIN
  IF EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_schema='public' AND table_name='transactions' AND column_name='id' AND is_identity='NO'
  ) THEN
    ALTER TABLE public.transactions ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY;
  END IF;
END $$;

-- 3) Defaults expected by Prisma.
ALTER TABLE public.users
  ALTER COLUMN "createdAt" SET DEFAULT now(),
  ALTER COLUMN "updatedAt" SET DEFAULT now();

ALTER TABLE public.categories
  ALTER COLUMN "isSystem" SET DEFAULT false,
  ALTER COLUMN "createdAt" SET DEFAULT now(),
  ALTER COLUMN "updatedAt" SET DEFAULT now();

ALTER TABLE public.financial_accounts
  ALTER COLUMN "isActive" SET DEFAULT true,
  ALTER COLUMN "createdAt" SET DEFAULT now(),
  ALTER COLUMN "updatedAt" SET DEFAULT now();

ALTER TABLE public.goals
  ALTER COLUMN "currentAmount" SET DEFAULT 0,
  ALTER COLUMN "startDate" SET DEFAULT now(),
  ALTER COLUMN "createdAt" SET DEFAULT now(),
  ALTER COLUMN "updatedAt" SET DEFAULT now();

ALTER TABLE public.investments
  ALTER COLUMN "totalInvested" SET DEFAULT 0,
  ALTER COLUMN "currentValue" SET DEFAULT 0,
  ALTER COLUMN "createdAt" SET DEFAULT now(),
  ALTER COLUMN "updatedAt" SET DEFAULT now();

ALTER TABLE public.investment_asset_taxonomy
  ALTER COLUMN "sortOrder" SET DEFAULT 0,
  ALTER COLUMN "isActive" SET DEFAULT true,
  ALTER COLUMN "createdAt" SET DEFAULT now(),
  ALTER COLUMN "updatedAt" SET DEFAULT now();

-- 3.0) User ownership for investment asset taxonomy.
ALTER TABLE IF EXISTS public.investment_asset_taxonomy
  ADD COLUMN IF NOT EXISTS "userId" INTEGER;

UPDATE public.investment_asset_taxonomy t
SET "userId" = i."userId"
FROM public.investments i
WHERE i."assetTaxonomyId" = t."id"
  AND t."userId" IS NULL;

UPDATE public.investment_asset_taxonomy t
SET "userId" = u."id"
FROM (
  SELECT MIN("id") AS "id" FROM public.users
) u
WHERE t."userId" IS NULL
  AND u."id" IS NOT NULL;

ALTER TABLE public.investment_asset_taxonomy
  ALTER COLUMN "userId" SET NOT NULL;

ALTER TABLE public.transactions
  ALTER COLUMN "date" SET DEFAULT now(),
  ALTER COLUMN "createdAt" SET DEFAULT now(),
  ALTER COLUMN "updatedAt" SET DEFAULT now();

ALTER TABLE public.investment_events
  ALTER COLUMN "createdAt" SET DEFAULT now(),
  ALTER COLUMN "updatedAt" SET DEFAULT now();

ALTER TABLE public.investment_contribution_plans
  ALTER COLUMN "autoCreateEvent" SET DEFAULT false,
  ALTER COLUMN "createdAt" SET DEFAULT now(),
  ALTER COLUMN "updatedAt" SET DEFAULT now();

-- 3.0.1) Create Prisma enum types if missing.
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM pg_type t
    JOIN pg_namespace n ON n.oid = t.typnamespace
    WHERE t.typname = 'HistoricalImportMode' AND n.nspname = 'public'
  ) THEN
    CREATE TYPE public."HistoricalImportMode" AS ENUM (
      'GENERATE_ALL',
      'MANUAL_REVIEW',
      'OPENING_BALANCE',
      'TRACK_FROM_TODAY'
    );
  END IF;

  IF NOT EXISTS (
    SELECT 1
    FROM pg_type t
    JOIN pg_namespace n ON n.oid = t.typnamespace
    WHERE t.typname = 'InvestmentEventStatus' AND n.nspname = 'public'
  ) THEN
    CREATE TYPE public."InvestmentEventStatus" AS ENUM (
      'EXPECTED',
      'PENDING',
      'CONFIRMED',
      'SKIPPED',
      'FAILED',
      'CANCELLED'
    );
  END IF;

  IF NOT EXISTS (
    SELECT 1
    FROM pg_type t
    JOIN pg_namespace n ON n.oid = t.typnamespace
    WHERE t.typname = 'InvestmentEventSource' AND n.nspname = 'public'
  ) THEN
    CREATE TYPE public."InvestmentEventSource" AS ENUM (
      'MANUAL',
      'RECURRING_PLAN',
      'HISTORICAL_IMPORT',
      'BANK_IMPORT',
      'BROKER_IMPORT',
      'SYSTEM_GENERATED'
    );
  END IF;
END $$;

-- 3.1) Recurring investment schema extensions.
ALTER TABLE IF EXISTS public.investment_events
  ADD COLUMN IF NOT EXISTS "recurringPlanId" INTEGER NULL,
  ADD COLUMN IF NOT EXISTS "dueDate" TIMESTAMPTZ NULL,
  ADD COLUMN IF NOT EXISTS "status" public."InvestmentEventStatus",
  ADD COLUMN IF NOT EXISTS "eventSource" public."InvestmentEventSource",
  ADD COLUMN IF NOT EXISTS "sequenceNumber" INTEGER NULL;

UPDATE public.investment_events
SET "status" = 'PENDING'
WHERE "status" IS NULL;

UPDATE public.investment_events
SET "eventSource" = 'MANUAL'
WHERE "eventSource" IS NULL;

ALTER TABLE public.investment_events
  ALTER COLUMN "status" DROP DEFAULT,
  ALTER COLUMN "eventSource" DROP DEFAULT;

ALTER TABLE public.investment_events
  ALTER COLUMN "status" TYPE public."InvestmentEventStatus" USING "status"::public."InvestmentEventStatus",
  ALTER COLUMN "eventSource" TYPE public."InvestmentEventSource" USING "eventSource"::public."InvestmentEventSource",
  ALTER COLUMN "status" SET NOT NULL,
  ALTER COLUMN "status" SET DEFAULT 'PENDING'::public."InvestmentEventStatus",
  ALTER COLUMN "eventSource" SET NOT NULL,
  ALTER COLUMN "eventSource" SET DEFAULT 'MANUAL'::public."InvestmentEventSource";

ALTER TABLE IF EXISTS public.investment_events
  ALTER COLUMN "amount" TYPE DECIMAL(18,2) USING "amount"::DECIMAL(18,2),
  ALTER COLUMN "pricePerUnit" TYPE DECIMAL(18,2) USING "pricePerUnit"::DECIMAL(18,2),
  ALTER COLUMN "netAmount" TYPE DECIMAL(18,2) USING "netAmount"::DECIMAL(18,2);

ALTER TABLE IF EXISTS public.investment_contribution_plans
  ADD COLUMN IF NOT EXISTS "historicalImportMode" public."HistoricalImportMode",
  ADD COLUMN IF NOT EXISTS "lastGeneratedDueDate" TIMESTAMPTZ NULL;

UPDATE public.investment_contribution_plans
SET "historicalImportMode" = 'MANUAL_REVIEW'
WHERE "historicalImportMode" IS NULL;

ALTER TABLE public.investment_contribution_plans
  ALTER COLUMN "historicalImportMode" DROP DEFAULT;

ALTER TABLE public.investment_contribution_plans
  ALTER COLUMN "historicalImportMode" TYPE public."HistoricalImportMode" USING "historicalImportMode"::public."HistoricalImportMode",
  ALTER COLUMN "historicalImportMode" SET NOT NULL,
  ALTER COLUMN "historicalImportMode" SET DEFAULT 'MANUAL_REVIEW'::public."HistoricalImportMode";

ALTER TABLE IF EXISTS public.investment_contribution_plans
  ALTER COLUMN "amount" TYPE DECIMAL(18,2) USING "amount"::DECIMAL(18,2);

ALTER TABLE public.valuation_snapshots
  ALTER COLUMN "createdAt" SET DEFAULT now();

-- 4) Enforce users auth identifier constraints from Prisma.
-- userId: optional, unique, VARCHAR(30)
-- email: required, unique
-- mobile: optional, unique, VARCHAR(15)
DO $$
BEGIN
  IF EXISTS (
    SELECT 1
    FROM public.users
    WHERE "userId" IS NOT NULL AND length("userId") > 30
  ) THEN
    RAISE EXCEPTION 'users.userId has values longer than 30 characters';
  END IF;

  IF EXISTS (
    SELECT 1
    FROM public.users
    WHERE "mobile" IS NOT NULL AND length("mobile") > 15
  ) THEN
    RAISE EXCEPTION 'users.mobile has values longer than 15 characters';
  END IF;

  IF EXISTS (
    SELECT 1
    FROM public.users
    WHERE "userId" IS NOT NULL
    GROUP BY "userId"
    HAVING COUNT(*) > 1
  ) THEN
    RAISE EXCEPTION 'duplicate non-null values found in users.userId';
  END IF;

  IF EXISTS (
    SELECT 1
    FROM public.users
    GROUP BY "email"
    HAVING COUNT(*) > 1
  ) THEN
    RAISE EXCEPTION 'duplicate values found in users.email';
  END IF;

  IF EXISTS (
    SELECT 1
    FROM public.users
    WHERE "mobile" IS NOT NULL
    GROUP BY "mobile"
    HAVING COUNT(*) > 1
  ) THEN
    RAISE EXCEPTION 'duplicate non-null values found in users.mobile';
  END IF;
END $$;

ALTER TABLE public.users
  ALTER COLUMN "userId" TYPE VARCHAR(30) USING "userId"::VARCHAR(30),
  ALTER COLUMN "mobile" TYPE VARCHAR(15) USING "mobile"::VARCHAR(15);

ALTER TABLE public.users
  DROP CONSTRAINT IF EXISTS "users_userId_key",
  DROP CONSTRAINT IF EXISTS "users_email_key",
  DROP CONSTRAINT IF EXISTS "users_mobile_key";

ALTER TABLE public.users
  ADD CONSTRAINT "users_userId_key" UNIQUE ("userId"),
  ADD CONSTRAINT "users_email_key" UNIQUE ("email"),
  ADD CONSTRAINT "users_mobile_key" UNIQUE ("mobile");

-- 5) Recreate FK actions to match Prisma onDelete behavior.
ALTER TABLE public.categories
  DROP CONSTRAINT IF EXISTS "categories_userId_fkey";
ALTER TABLE public.categories
  ADD CONSTRAINT "categories_userId_fkey"
  FOREIGN KEY ("userId") REFERENCES public.users("id") ON DELETE CASCADE;

ALTER TABLE public.financial_accounts
  DROP CONSTRAINT IF EXISTS "financial_accounts_userId_fkey";
ALTER TABLE public.financial_accounts
  ADD CONSTRAINT "financial_accounts_userId_fkey"
  FOREIGN KEY ("userId") REFERENCES public.users("id") ON DELETE CASCADE;

ALTER TABLE public.goals
  DROP CONSTRAINT IF EXISTS "goals_userId_fkey",
  DROP CONSTRAINT IF EXISTS "goals_categoryId_fkey";
ALTER TABLE public.goals
  ADD CONSTRAINT "goals_userId_fkey"
  FOREIGN KEY ("userId") REFERENCES public.users("id") ON DELETE CASCADE,
  ADD CONSTRAINT "goals_categoryId_fkey"
  FOREIGN KEY ("categoryId") REFERENCES public.categories("id") ON DELETE RESTRICT;

ALTER TABLE public.investments
  DROP CONSTRAINT IF EXISTS "investments_userId_fkey",
  DROP CONSTRAINT IF EXISTS "investments_accountId_fkey",
  DROP CONSTRAINT IF EXISTS "investments_assetTaxonomyId_fkey";
ALTER TABLE public.investments
  ADD CONSTRAINT "investments_userId_fkey"
  FOREIGN KEY ("userId") REFERENCES public.users("id") ON DELETE CASCADE,
  ADD CONSTRAINT "investments_accountId_fkey"
  FOREIGN KEY ("accountId") REFERENCES public.financial_accounts("id") ON DELETE SET NULL,
  ADD CONSTRAINT "investments_assetTaxonomyId_fkey"
  FOREIGN KEY ("assetTaxonomyId") REFERENCES public.investment_asset_taxonomy("id") ON DELETE SET NULL;

ALTER TABLE public.investment_asset_taxonomy
  DROP CONSTRAINT IF EXISTS "investment_asset_taxonomy_parentId_fkey",
  DROP CONSTRAINT IF EXISTS "investment_asset_taxonomy_userId_fkey";
ALTER TABLE public.investment_asset_taxonomy
  ADD CONSTRAINT "investment_asset_taxonomy_userId_fkey"
  FOREIGN KEY ("userId") REFERENCES public.users("id") ON DELETE CASCADE,
  ADD CONSTRAINT "investment_asset_taxonomy_parentId_fkey"
  FOREIGN KEY ("parentId") REFERENCES public.investment_asset_taxonomy("id") ON DELETE SET NULL;

ALTER TABLE public.transactions
  DROP CONSTRAINT IF EXISTS "transactions_userId_fkey",
  DROP CONSTRAINT IF EXISTS "transactions_categoryId_fkey",
  DROP CONSTRAINT IF EXISTS "transactions_goalId_fkey",
  DROP CONSTRAINT IF EXISTS "transactions_sourceAccountId_fkey",
  DROP CONSTRAINT IF EXISTS "transactions_destinationAccountId_fkey";
ALTER TABLE public.transactions
  ADD CONSTRAINT "transactions_userId_fkey"
  FOREIGN KEY ("userId") REFERENCES public.users("id") ON DELETE CASCADE,
  ADD CONSTRAINT "transactions_categoryId_fkey"
  FOREIGN KEY ("categoryId") REFERENCES public.categories("id") ON DELETE RESTRICT,
  ADD CONSTRAINT "transactions_goalId_fkey"
  FOREIGN KEY ("goalId") REFERENCES public.goals("id") ON DELETE SET NULL,
  ADD CONSTRAINT "transactions_sourceAccountId_fkey"
  FOREIGN KEY ("sourceAccountId") REFERENCES public.financial_accounts("id") ON DELETE SET NULL,
  ADD CONSTRAINT "transactions_destinationAccountId_fkey"
  FOREIGN KEY ("destinationAccountId") REFERENCES public.financial_accounts("id") ON DELETE SET NULL;

ALTER TABLE public.investment_events
  DROP CONSTRAINT IF EXISTS "investment_events_investmentId_fkey",
  DROP CONSTRAINT IF EXISTS "investment_events_sourceAccountId_fkey",
  DROP CONSTRAINT IF EXISTS "investment_events_recurringPlanId_fkey";
ALTER TABLE public.investment_events
  ADD CONSTRAINT "investment_events_investmentId_fkey"
  FOREIGN KEY ("investmentId") REFERENCES public.investments("id") ON DELETE CASCADE,
  ADD CONSTRAINT "investment_events_recurringPlanId_fkey"
  FOREIGN KEY ("recurringPlanId") REFERENCES public.investment_contribution_plans("id") ON DELETE SET NULL,
  ADD CONSTRAINT "investment_events_sourceAccountId_fkey"
  FOREIGN KEY ("sourceAccountId") REFERENCES public.financial_accounts("id") ON DELETE SET NULL;

ALTER TABLE public.investment_contribution_plans
  DROP CONSTRAINT IF EXISTS "investment_contribution_plans_investmentId_fkey",
  DROP CONSTRAINT IF EXISTS "investment_contribution_plans_sourceAccountId_fkey";
ALTER TABLE public.investment_contribution_plans
  ADD CONSTRAINT "investment_contribution_plans_investmentId_fkey"
  FOREIGN KEY ("investmentId") REFERENCES public.investments("id") ON DELETE CASCADE,
  ADD CONSTRAINT "investment_contribution_plans_sourceAccountId_fkey"
  FOREIGN KEY ("sourceAccountId") REFERENCES public.financial_accounts("id") ON DELETE SET NULL;

ALTER TABLE public.valuation_snapshots
  DROP CONSTRAINT IF EXISTS "valuation_snapshots_userId_fkey",
  DROP CONSTRAINT IF EXISTS "valuation_snapshots_investmentId_fkey";
ALTER TABLE public.valuation_snapshots
  ADD CONSTRAINT "valuation_snapshots_userId_fkey"
  FOREIGN KEY ("userId") REFERENCES public.users("id") ON DELETE CASCADE,
  ADD CONSTRAINT "valuation_snapshots_investmentId_fkey"
  FOREIGN KEY ("investmentId") REFERENCES public.investments("id") ON DELETE CASCADE;

-- Recreate circular links with Prisma semantics.
ALTER TABLE public.transactions
  ADD CONSTRAINT "transactions_linkedInvestmentEventId_fkey"
  FOREIGN KEY ("linkedInvestmentEventId") REFERENCES public.investment_events("id") ON DELETE SET NULL;

ALTER TABLE public.investment_events
  ADD CONSTRAINT "investment_events_linkedTransactionId_fkey"
  FOREIGN KEY ("linkedTransactionId") REFERENCES public.transactions("id") ON DELETE SET NULL;

-- 6) Indexes from Prisma.
CREATE INDEX IF NOT EXISTS "transactions_userId_idx" ON public.transactions ("userId");
CREATE INDEX IF NOT EXISTS "transactions_date_idx" ON public.transactions ("date");
CREATE INDEX IF NOT EXISTS "transactions_type_idx" ON public.transactions ("type");
CREATE INDEX IF NOT EXISTS "transactions_goalId_idx" ON public.transactions ("goalId");
CREATE INDEX IF NOT EXISTS "transactions_categoryId_idx" ON public.transactions ("categoryId");
CREATE INDEX IF NOT EXISTS "transactions_sourceAccountId_idx" ON public.transactions ("sourceAccountId");
CREATE INDEX IF NOT EXISTS "transactions_destinationAccountId_idx" ON public.transactions ("destinationAccountId");

CREATE INDEX IF NOT EXISTS "goals_userId_idx" ON public.goals ("userId");
CREATE INDEX IF NOT EXISTS "goals_categoryId_idx" ON public.goals ("categoryId");

CREATE INDEX IF NOT EXISTS "categories_userId_idx" ON public.categories ("userId");
CREATE INDEX IF NOT EXISTS "financial_accounts_userId_idx" ON public.financial_accounts ("userId");

CREATE INDEX IF NOT EXISTS "investments_userId_idx" ON public.investments ("userId");
CREATE INDEX IF NOT EXISTS "investments_accountId_idx" ON public.investments ("accountId");
CREATE INDEX IF NOT EXISTS "investments_assetTaxonomyId_idx" ON public.investments ("assetTaxonomyId");

CREATE INDEX IF NOT EXISTS "investment_asset_taxonomy_parentId_idx" ON public.investment_asset_taxonomy ("parentId");
CREATE INDEX IF NOT EXISTS "investment_asset_taxonomy_userId_idx" ON public.investment_asset_taxonomy ("userId");
CREATE INDEX IF NOT EXISTS "investment_asset_taxonomy_nodeType_idx" ON public.investment_asset_taxonomy ("nodeType");
CREATE INDEX IF NOT EXISTS "investment_asset_taxonomy_level_idx" ON public.investment_asset_taxonomy ("level");

CREATE INDEX IF NOT EXISTS "investment_events_investmentId_idx" ON public.investment_events ("investmentId");
CREATE INDEX IF NOT EXISTS "investment_events_recurringPlanId_idx" ON public.investment_events ("recurringPlanId");
CREATE INDEX IF NOT EXISTS "investment_events_dueDate_idx" ON public.investment_events ("dueDate");
CREATE INDEX IF NOT EXISTS "investment_events_status_idx" ON public.investment_events ("status");
CREATE INDEX IF NOT EXISTS "investment_events_sourceAccountId_idx" ON public.investment_events ("sourceAccountId");
CREATE UNIQUE INDEX IF NOT EXISTS "investment_events_recurringPlanId_dueDate_eventType_key"
  ON public.investment_events ("recurringPlanId", "dueDate", "eventType");

CREATE INDEX IF NOT EXISTS "investment_contribution_plans_investmentId_idx" ON public.investment_contribution_plans ("investmentId");
CREATE INDEX IF NOT EXISTS "investment_contribution_plans_sourceAccountId_idx" ON public.investment_contribution_plans ("sourceAccountId");
CREATE INDEX IF NOT EXISTS "investment_contribution_plans_status_idx" ON public.investment_contribution_plans ("status");
CREATE INDEX IF NOT EXISTS "investment_contribution_plans_nextDueDate_idx" ON public.investment_contribution_plans ("nextDueDate");

CREATE INDEX IF NOT EXISTS "valuation_snapshots_userId_idx" ON public.valuation_snapshots ("userId");
CREATE INDEX IF NOT EXISTS "valuation_snapshots_investmentId_idx" ON public.valuation_snapshots ("investmentId");
CREATE INDEX IF NOT EXISTS "valuation_snapshots_snapshotDate_idx" ON public.valuation_snapshots ("snapshotDate");

COMMIT;
