-- Core schema generated from server/src/domain/types.ts and docs/data-model/INVESTMENT_ER_DIAGRAM.md
-- Target: PostgreSQL / Supabase
-- Notes:
-- 1) No seed data included.
-- 2) DDL is aligned with server/prisma/schema.prisma for production use.
-- 3) Column names preserve canonical model field names using quoted identifiers.

BEGIN;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM pg_type t
    JOIN pg_namespace n ON n.oid = t.typnamespace
    WHERE t.typname = 'HistoricalImportMode' AND n.nspname = 'public'
  ) THEN
    CREATE TYPE public."HistoricalImportMode" AS ENUM (
      'GENERATE_ALL',
      'MANUAL_REVIEW',
      'OPENING_BALANCE',
      'TRACK_FROM_TODAY'
    );
  END IF;

  IF NOT EXISTS (
    SELECT 1
    FROM pg_type t
    JOIN pg_namespace n ON n.oid = t.typnamespace
    WHERE t.typname = 'InvestmentEventStatus' AND n.nspname = 'public'
  ) THEN
    CREATE TYPE public."InvestmentEventStatus" AS ENUM (
      'EXPECTED',
      'PENDING',
      'CONFIRMED',
      'SKIPPED',
      'FAILED',
      'CANCELLED'
    );
  END IF;

  IF NOT EXISTS (
    SELECT 1
    FROM pg_type t
    JOIN pg_namespace n ON n.oid = t.typnamespace
    WHERE t.typname = 'InvestmentEventSource' AND n.nspname = 'public'
  ) THEN
    CREATE TYPE public."InvestmentEventSource" AS ENUM (
      'MANUAL',
      'RECURRING_PLAN',
      'HISTORICAL_IMPORT',
      'BANK_IMPORT',
      'BROKER_IMPORT',
      'SYSTEM_GENERATED'
    );
  END IF;
END $$;

CREATE TABLE IF NOT EXISTS public.users (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "userId" VARCHAR(30) NULL UNIQUE,
  "email" TEXT NOT NULL UNIQUE,
  "mobile" VARCHAR(15) NULL UNIQUE,
  "password" TEXT NOT NULL,
  "name" TEXT NULL,
  "createdAt" TIMESTAMPTZ NOT NULL DEFAULT now(),
  "updatedAt" TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.categories (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "userId" INTEGER NOT NULL,
  "name" TEXT NOT NULL,
  "type" TEXT NOT NULL,
  "icon" TEXT NULL,
  "color" TEXT NULL,
  "isSystem" BOOLEAN NOT NULL DEFAULT false,
  "createdAt" TIMESTAMPTZ NOT NULL DEFAULT now(),
  "updatedAt" TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT "categories_userId_fkey"
    FOREIGN KEY ("userId") REFERENCES public.users("id") ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS public.financial_accounts (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "userId" INTEGER NOT NULL,
  "name" TEXT NOT NULL,
  "displayName" TEXT NOT NULL,
  "accountType" TEXT NOT NULL,
  "institutionName" TEXT NULL,
  "accountNumberMasked" TEXT NULL,
  "currency" TEXT NOT NULL,
  "isActive" BOOLEAN NOT NULL DEFAULT true,
  "createdAt" TIMESTAMPTZ NOT NULL DEFAULT now(),
  "updatedAt" TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT "financial_accounts_userId_fkey"
    FOREIGN KEY ("userId") REFERENCES public.users("id") ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS public.investment_asset_taxonomy (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "userId" INTEGER NOT NULL,
  "label" TEXT NOT NULL,
  "nodeType" TEXT NOT NULL,
  "level" INTEGER NOT NULL,
  "parentId" INTEGER NULL,
  "sortOrder" INTEGER NOT NULL DEFAULT 0,
  "isActive" BOOLEAN NOT NULL DEFAULT true,
  "createdAt" TIMESTAMPTZ NOT NULL DEFAULT now(),
  "updatedAt" TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT "investment_asset_taxonomy_userId_fkey"
    FOREIGN KEY ("userId") REFERENCES public.users("id") ON DELETE CASCADE,
  CONSTRAINT "investment_asset_taxonomy_parentId_fkey"
    FOREIGN KEY ("parentId") REFERENCES public.investment_asset_taxonomy("id") ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS public.goals (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "userId" INTEGER NOT NULL,
  "categoryId" INTEGER NOT NULL,
  "name" TEXT NOT NULL,
  "description" TEXT NULL,
  "icon" TEXT NULL,
  "targetAmount" DOUBLE PRECISION NOT NULL,
  "currentAmount" DOUBLE PRECISION NOT NULL DEFAULT 0,
  "startDate" TIMESTAMPTZ NOT NULL DEFAULT now(),
  "deadline" TIMESTAMPTZ NULL,
  "categoryLabelSnapshot" TEXT NOT NULL,
  "createdAt" TIMESTAMPTZ NOT NULL DEFAULT now(),
  "updatedAt" TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT "goals_userId_fkey"
    FOREIGN KEY ("userId") REFERENCES public.users("id") ON DELETE CASCADE,
  CONSTRAINT "goals_categoryId_fkey"
    FOREIGN KEY ("categoryId") REFERENCES public.categories("id") ON DELETE RESTRICT
);

CREATE TABLE IF NOT EXISTS public.investments (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "userId" INTEGER NOT NULL,
  "accountId" INTEGER NULL,
  "assetTaxonomyId" INTEGER NULL,
  "name" TEXT NOT NULL,
  "assetType" TEXT NOT NULL,
  "assetCategory" TEXT NOT NULL,
  "holdingMode" TEXT NULL,
  "institutionName" TEXT NULL,
  "referenceNumber" TEXT NULL,
  "status" TEXT NOT NULL,
  "startDate" TIMESTAMPTZ NULL,
  "maturityDate" TIMESTAMPTZ NULL,
  "currency" TEXT NOT NULL,
  "totalInvested" DOUBLE PRECISION NOT NULL DEFAULT 0,
  "currentValue" DOUBLE PRECISION NOT NULL DEFAULT 0,
  "currentValueSource" TEXT NULL,
  "lastValuationAt" TIMESTAMPTZ NULL,
  "insuranceCover" DOUBLE PRECISION NULL,
  "contributionMode" TEXT NULL,
  "notes" TEXT NULL,
  "documentsMeta" JSONB NULL,
  "createdAt" TIMESTAMPTZ NOT NULL DEFAULT now(),
  "updatedAt" TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT "investments_userId_fkey"
    FOREIGN KEY ("userId") REFERENCES public.users("id") ON DELETE CASCADE,
  CONSTRAINT "investments_accountId_fkey"
    FOREIGN KEY ("accountId") REFERENCES public.financial_accounts("id") ON DELETE SET NULL,
  CONSTRAINT "investments_assetTaxonomyId_fkey"
    FOREIGN KEY ("assetTaxonomyId") REFERENCES public.investment_asset_taxonomy("id") ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS public.transactions (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "userId" INTEGER NOT NULL,
  "categoryId" INTEGER NOT NULL,
  "goalId" INTEGER NULL,
  "sourceAccountId" INTEGER NULL,
  "destinationAccountId" INTEGER NULL,
  "linkedInvestmentEventId" INTEGER NULL,
  "type" TEXT NOT NULL,
  "transactionKind" TEXT NOT NULL,
  "amount" DOUBLE PRECISION NOT NULL,
  "categoryLabelSnapshot" TEXT NOT NULL,
  "date" TIMESTAMPTZ NOT NULL DEFAULT now(),
  "notes" TEXT NULL,
  "createdAt" TIMESTAMPTZ NOT NULL DEFAULT now(),
  "updatedAt" TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT "transactions_userId_fkey"
    FOREIGN KEY ("userId") REFERENCES public.users("id") ON DELETE CASCADE,
  CONSTRAINT "transactions_categoryId_fkey"
    FOREIGN KEY ("categoryId") REFERENCES public.categories("id") ON DELETE RESTRICT,
  CONSTRAINT "transactions_goalId_fkey"
    FOREIGN KEY ("goalId") REFERENCES public.goals("id") ON DELETE SET NULL,
  CONSTRAINT "transactions_sourceAccountId_fkey"
    FOREIGN KEY ("sourceAccountId") REFERENCES public.financial_accounts("id") ON DELETE SET NULL,
  CONSTRAINT "transactions_destinationAccountId_fkey"
    FOREIGN KEY ("destinationAccountId") REFERENCES public.financial_accounts("id") ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS public.investment_events (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "investmentId" INTEGER NOT NULL,
  "recurringPlanId" INTEGER NULL,
  "sourceAccountId" INTEGER NULL,
  "linkedTransactionId" INTEGER NULL,
  "eventType" TEXT NOT NULL,
  "dueDate" TIMESTAMPTZ NULL,
  "status" public."InvestmentEventStatus" NOT NULL DEFAULT 'PENDING',
  "eventSource" public."InvestmentEventSource" NOT NULL DEFAULT 'MANUAL',
  "sequenceNumber" INTEGER NULL,
  "eventDate" TIMESTAMPTZ NOT NULL,
  "amount" DECIMAL(18,2) NULL,
  "units" DOUBLE PRECISION NULL,
  "pricePerUnit" DECIMAL(18,2) NULL,
  "netAmount" DECIMAL(18,2) NULL,
  "notes" TEXT NULL,
  "meta" JSONB NULL,
  "createdAt" TIMESTAMPTZ NOT NULL DEFAULT now(),
  "updatedAt" TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT "investment_events_investmentId_fkey"
    FOREIGN KEY ("investmentId") REFERENCES public.investments("id") ON DELETE CASCADE,
  CONSTRAINT "investment_events_recurringPlanId_fkey"
    FOREIGN KEY ("recurringPlanId") REFERENCES public.investment_contribution_plans("id") ON DELETE SET NULL,
  CONSTRAINT "investment_events_sourceAccountId_fkey"
    FOREIGN KEY ("sourceAccountId") REFERENCES public.financial_accounts("id") ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS public.investment_contribution_plans (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "investmentId" INTEGER NOT NULL,
  "sourceAccountId" INTEGER NULL,
  "status" TEXT NOT NULL,
  "amount" DECIMAL(18,2) NOT NULL,
  "cadenceUnit" TEXT NOT NULL,
  "cadenceInterval" INTEGER NOT NULL,
  "historicalImportMode" public."HistoricalImportMode" NOT NULL DEFAULT 'MANUAL_REVIEW',
  "anchorDate" TIMESTAMPTZ NOT NULL,
  "lastGeneratedDueDate" TIMESTAMPTZ NULL,
  "nextDueDate" TIMESTAMPTZ NULL,
  "endDate" TIMESTAMPTZ NULL,
  "reminderDaysBefore" INTEGER NULL,
  "autoCreateEvent" BOOLEAN NOT NULL DEFAULT false,
  "notes" TEXT NULL,
  "createdAt" TIMESTAMPTZ NOT NULL DEFAULT now(),
  "updatedAt" TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT "investment_contribution_plans_investmentId_fkey"
    FOREIGN KEY ("investmentId") REFERENCES public.investments("id") ON DELETE CASCADE,
  CONSTRAINT "investment_contribution_plans_sourceAccountId_fkey"
    FOREIGN KEY ("sourceAccountId") REFERENCES public.financial_accounts("id") ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS public.valuation_snapshots (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "userId" INTEGER NOT NULL,
  "investmentId" INTEGER NOT NULL,
  "snapshotDate" TIMESTAMPTZ NOT NULL,
  "marketValue" DOUBLE PRECISION NOT NULL,
  "units" DOUBLE PRECISION NULL,
  "price" DOUBLE PRECISION NULL,
  "source" TEXT NULL,
  "createdAt" TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT "valuation_snapshots_userId_fkey"
    FOREIGN KEY ("userId") REFERENCES public.users("id") ON DELETE CASCADE,
  CONSTRAINT "valuation_snapshots_investmentId_fkey"
    FOREIGN KEY ("investmentId") REFERENCES public.investments("id") ON DELETE CASCADE
);

-- Add circular cross references after both tables exist.
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'transactions_linkedInvestmentEventId_fkey'
  ) THEN
    ALTER TABLE public.transactions
      ADD CONSTRAINT "transactions_linkedInvestmentEventId_fkey"
      FOREIGN KEY ("linkedInvestmentEventId") REFERENCES public.investment_events("id") ON DELETE SET NULL;
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'investment_events_linkedTransactionId_fkey'
  ) THEN
    ALTER TABLE public.investment_events
      ADD CONSTRAINT "investment_events_linkedTransactionId_fkey"
      FOREIGN KEY ("linkedTransactionId") REFERENCES public.transactions("id") ON DELETE SET NULL;
  END IF;
END $$;

-- Indexes aligned with Prisma model.
CREATE INDEX IF NOT EXISTS "transactions_userId_idx" ON public.transactions ("userId");
CREATE INDEX IF NOT EXISTS "transactions_date_idx" ON public.transactions ("date");
CREATE INDEX IF NOT EXISTS "transactions_type_idx" ON public.transactions ("type");
CREATE INDEX IF NOT EXISTS "transactions_goalId_idx" ON public.transactions ("goalId");
CREATE INDEX IF NOT EXISTS "transactions_categoryId_idx" ON public.transactions ("categoryId");
CREATE INDEX IF NOT EXISTS "transactions_sourceAccountId_idx" ON public.transactions ("sourceAccountId");
CREATE INDEX IF NOT EXISTS "transactions_destinationAccountId_idx" ON public.transactions ("destinationAccountId");

CREATE INDEX IF NOT EXISTS "goals_userId_idx" ON public.goals ("userId");
CREATE INDEX IF NOT EXISTS "goals_categoryId_idx" ON public.goals ("categoryId");

CREATE INDEX IF NOT EXISTS "categories_userId_idx" ON public.categories ("userId");
CREATE INDEX IF NOT EXISTS "financial_accounts_userId_idx" ON public.financial_accounts ("userId");

CREATE INDEX IF NOT EXISTS "investments_userId_idx" ON public.investments ("userId");
CREATE INDEX IF NOT EXISTS "investments_accountId_idx" ON public.investments ("accountId");
CREATE INDEX IF NOT EXISTS "investments_assetTaxonomyId_idx" ON public.investments ("assetTaxonomyId");

CREATE INDEX IF NOT EXISTS "investment_asset_taxonomy_parentId_idx" ON public.investment_asset_taxonomy ("parentId");
CREATE INDEX IF NOT EXISTS "investment_asset_taxonomy_userId_idx" ON public.investment_asset_taxonomy ("userId");
CREATE INDEX IF NOT EXISTS "investment_asset_taxonomy_nodeType_idx" ON public.investment_asset_taxonomy ("nodeType");
CREATE INDEX IF NOT EXISTS "investment_asset_taxonomy_level_idx" ON public.investment_asset_taxonomy ("level");

CREATE INDEX IF NOT EXISTS "investment_events_investmentId_idx" ON public.investment_events ("investmentId");
CREATE INDEX IF NOT EXISTS "investment_events_recurringPlanId_idx" ON public.investment_events ("recurringPlanId");
CREATE INDEX IF NOT EXISTS "investment_events_dueDate_idx" ON public.investment_events ("dueDate");
CREATE INDEX IF NOT EXISTS "investment_events_status_idx" ON public.investment_events ("status");
CREATE INDEX IF NOT EXISTS "investment_events_sourceAccountId_idx" ON public.investment_events ("sourceAccountId");
CREATE UNIQUE INDEX IF NOT EXISTS "investment_events_recurringPlanId_dueDate_eventType_key"
  ON public.investment_events ("recurringPlanId", "dueDate", "eventType");

CREATE INDEX IF NOT EXISTS "investment_contribution_plans_investmentId_idx" ON public.investment_contribution_plans ("investmentId");
CREATE INDEX IF NOT EXISTS "investment_contribution_plans_sourceAccountId_idx" ON public.investment_contribution_plans ("sourceAccountId");
CREATE INDEX IF NOT EXISTS "investment_contribution_plans_status_idx" ON public.investment_contribution_plans ("status");
CREATE INDEX IF NOT EXISTS "investment_contribution_plans_nextDueDate_idx" ON public.investment_contribution_plans ("nextDueDate");

CREATE INDEX IF NOT EXISTS "valuation_snapshots_userId_idx" ON public.valuation_snapshots ("userId");
CREATE INDEX IF NOT EXISTS "valuation_snapshots_investmentId_idx" ON public.valuation_snapshots ("investmentId");
CREATE INDEX IF NOT EXISTS "valuation_snapshots_snapshotDate_idx" ON public.valuation_snapshots ("snapshotDate");

COMMIT;
