-- Core schema generated from server/src/domain/types.ts and docs/data-model/INVESTMENT_ER_DIAGRAM.md
-- Target: PostgreSQL / Supabase
-- Notes:
-- 1) No transactional seed data included; canonical meta config reference rows are bootstrapped for integrity.
-- 2) DDL is aligned with server/prisma/schema.prisma for production use.
-- 3) Column names preserve canonical model field names using quoted identifiers.

BEGIN;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM pg_type t
    JOIN pg_namespace n ON n.oid = t.typnamespace
    WHERE t.typname = 'HistoricalImportMode' AND n.nspname = 'public'
  ) THEN
    CREATE TYPE public."HistoricalImportMode" AS ENUM (
      'OPENING_BALANCE',
      'TRACK_FROM_TODAY'
    );
  END IF;

  IF NOT EXISTS (
    SELECT 1
    FROM pg_type t
    JOIN pg_namespace n ON n.oid = t.typnamespace
    WHERE t.typname = 'InvestmentEventStatus' AND n.nspname = 'public'
  ) THEN
    CREATE TYPE public."InvestmentEventStatus" AS ENUM (
      'EXPECTED',
      'PENDING',
      'CONFIRMED',
      'SKIPPED',
      'FAILED',
      'CANCELLED'
    );
  END IF;

  IF NOT EXISTS (
    SELECT 1
    FROM pg_type t
    JOIN pg_namespace n ON n.oid = t.typnamespace
    WHERE t.typname = 'InvestmentEventSource' AND n.nspname = 'public'
  ) THEN
    CREATE TYPE public."InvestmentEventSource" AS ENUM (
      'MANUAL',
      'RECURRING_PLAN',
      'HISTORICAL_IMPORT',
      'BANK_IMPORT',
      'BROKER_IMPORT',
      'SYSTEM_GENERATED'
    );
  END IF;

  IF NOT EXISTS (
    SELECT 1
    FROM pg_type t
    JOIN pg_namespace n ON n.oid = t.typnamespace
    WHERE t.typname = 'InvestmentEventType' AND n.nspname = 'public'
  ) THEN
    CREATE TYPE public."InvestmentEventType" AS ENUM (
      'CONTRIBUTION',
      'OPENING_BALANCE',
      'OPENING_INCOME_CREDIT',
      'INCOME_CREDIT',
      'WITHDRAWAL_PRINCIPAL',
      'PREMIUM'
    );
  END IF;

  IF NOT EXISTS (
    SELECT 1
    FROM pg_type t
    JOIN pg_namespace n ON n.oid = t.typnamespace
    WHERE t.typname = 'InvestmentContributionMode' AND n.nspname = 'public'
  ) THEN
    CREATE TYPE public."InvestmentContributionMode" AS ENUM (
      'ONE_TIME',
      'RECURRING'
    );
  END IF;

  IF NOT EXISTS (
    SELECT 1
    FROM pg_type t
    JOIN pg_namespace n ON n.oid = t.typnamespace
    WHERE t.typname = 'AccountingTreatment' AND n.nspname = 'public'
  ) THEN
    CREATE TYPE public."AccountingTreatment" AS ENUM (
      'INVESTMENT',
      'INSURANCE_SAVINGS',
      'PROTECTION_EXPENSE'
    );
  END IF;

  IF NOT EXISTS (
    SELECT 1
    FROM pg_type t
    JOIN pg_namespace n ON n.oid = t.typnamespace
    WHERE t.typname = 'InvestmentBenefitType' AND n.nspname = 'public'
  ) THEN
    CREATE TYPE public."InvestmentBenefitType" AS ENUM (
      'MATURITY',
      'COUPON',
      'INTEREST',
      'PRINCIPAL_REDEMPTION',
      'ANNUITY',
      'MONEY_BACK',
      'SURVIVAL',
      'BONUS',
      'RETURN_OF_PREMIUM',
      'DEATH_BENEFIT',
      'OTHER'
    );
  END IF;

  IF NOT EXISTS (
    SELECT 1
    FROM pg_type t
    JOIN pg_namespace n ON n.oid = t.typnamespace
    WHERE t.typname = 'InvestmentBenefitStatus' AND n.nspname = 'public'
  ) THEN
    CREATE TYPE public."InvestmentBenefitStatus" AS ENUM (
      'EXPECTED',
      'RECEIVED',
      'CANCELLED'
    );
  END IF;

  IF NOT EXISTS (
    SELECT 1
    FROM pg_type t
    JOIN pg_namespace n ON n.oid = t.typnamespace
    WHERE t.typname = 'TransactionType' AND n.nspname = 'public'
  ) THEN
    CREATE TYPE public."TransactionType" AS ENUM (
      'INCOME',
      'EXPENSE',
      'TRANSFER',
      'INVESTMENT'
    );
  END IF;
END $$;

CREATE TABLE IF NOT EXISTS public.users (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "userId" VARCHAR(30) NULL UNIQUE,
  "email" TEXT NOT NULL UNIQUE,
  "mobile" VARCHAR(15) NULL UNIQUE,
  "password" TEXT NOT NULL,
  "name" TEXT NULL,
  "createdAt" TIMESTAMPTZ NOT NULL DEFAULT now(),
  "updatedAt" TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.categories (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "userId" INTEGER NOT NULL,
  "name" TEXT NOT NULL,
  "type" TEXT NOT NULL,
  "icon" TEXT NULL,
  "color" TEXT NULL,
  "isSystem" BOOLEAN NOT NULL DEFAULT false,
  "createdAt" TIMESTAMPTZ NOT NULL DEFAULT now(),
  "updatedAt" TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT "categories_userId_fkey"
    FOREIGN KEY ("userId") REFERENCES public.users("id") ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS public.financial_accounts (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "userId" INTEGER NOT NULL,
  "name" TEXT NOT NULL,
  "displayName" TEXT NOT NULL,
  "accountType" TEXT NOT NULL,
  "institutionName" TEXT NULL,
  "accountNumberMasked" TEXT NULL,
  "currency" TEXT NOT NULL,
  "isActive" BOOLEAN NOT NULL DEFAULT true,
  "openingBalance" DECIMAL(18,2) NOT NULL DEFAULT 0,
  "createdAt" TIMESTAMPTZ NOT NULL DEFAULT now(),
  "updatedAt" TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT "financial_accounts_userId_fkey"
    FOREIGN KEY ("userId") REFERENCES public.users("id") ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS public.app_meta_config_ref (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "module" TEXT NOT NULL,
  "configType" TEXT NOT NULL,
  "parentId" INTEGER NULL,
  "code" TEXT NOT NULL UNIQUE,
  "label" TEXT NOT NULL,
  "accountingTreatment" public."AccountingTreatment" NULL,
  "isActive" BOOLEAN NOT NULL DEFAULT true,
  "sortOrder" INTEGER NOT NULL DEFAULT 0,
  "createdAt" TIMESTAMPTZ NOT NULL DEFAULT now(),
  "updatedAt" TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT "app_meta_config_ref_parentId_fkey"
    FOREIGN KEY ("parentId") REFERENCES public.app_meta_config_ref("id") ON DELETE SET NULL
);

INSERT INTO public.app_meta_config_ref ("module", "configType", "parentId", "code", "label", "sortOrder", "accountingTreatment")
VALUES
  ('INVESTMENT', 'ASSET_TYPE', NULL, 'DEPOSIT', 'Deposit', 10, 'INVESTMENT'),
  ('INVESTMENT', 'ASSET_TYPE', NULL, 'EQUITY', 'Equity', 20, 'INVESTMENT'),
  ('INVESTMENT', 'ASSET_TYPE', NULL, 'DEBT', 'Debt', 30, 'INVESTMENT'),
  ('INVESTMENT', 'ASSET_TYPE', NULL, 'RETIREMENT', 'Retirement', 40, 'INVESTMENT'),
  -- INSURANCE has no type-level default: its categories mix INSURANCE_SAVINGS and PROTECTION_EXPENSE, so treatment is resolved per category.
  ('INVESTMENT', 'ASSET_TYPE', NULL, 'INSURANCE', 'Insurance', 50, NULL),
  ('INVESTMENT', 'ASSET_TYPE', NULL, 'COMMODITY', 'Commodity', 60, 'INVESTMENT'),
  ('INVESTMENT', 'ASSET_TYPE', NULL, 'REAL_ESTATE', 'Real Estate', 70, 'INVESTMENT'),
  ('INVESTMENT', 'ASSET_TYPE', NULL, 'ALTERNATIVE', 'Alternative', 80, 'INVESTMENT')
ON CONFLICT ("code") DO UPDATE
SET
  "module" = EXCLUDED."module",
  "configType" = EXCLUDED."configType",
  "parentId" = EXCLUDED."parentId",
  "label" = EXCLUDED."label",
  "sortOrder" = EXCLUDED."sortOrder",
  "accountingTreatment" = EXCLUDED."accountingTreatment",
  "isActive" = true,
  "updatedAt" = now();

INSERT INTO public.app_meta_config_ref ("module", "configType", "parentId", "code", "label", "sortOrder", "accountingTreatment")
SELECT 'INVESTMENT', 'ASSET_CATEGORY', parent."id", child."code", child."label", child."sortOrder", child."accountingTreatment"::public."AccountingTreatment"
FROM (
  VALUES
    ('DEPOSIT', 'BANK_DEPOSIT', 'Bank Deposit', 11, 'INVESTMENT'),
    ('DEPOSIT', 'FIXED_DEPOSIT', 'Fixed Deposit', 12, 'INVESTMENT'),
    ('DEPOSIT', 'RECURRING_DEPOSIT', 'Recurring Deposit', 13, 'INVESTMENT'),
    ('EQUITY', 'STOCK', 'Stock', 21, 'INVESTMENT'),
    ('EQUITY', 'MUTUAL_FUND', 'Mutual Fund', 22, 'INVESTMENT'),
    ('EQUITY', 'ETF', 'ETF', 23, 'INVESTMENT'),
    ('EQUITY', 'INDEX_FUND', 'Index Fund', 24, 'INVESTMENT'),
    ('DEBT', 'BOND', 'Bond', 31, 'INVESTMENT'),
    ('DEBT', 'DEBT_MUTUAL_FUND', 'Debt Mutual Fund', 32, 'INVESTMENT'),
    ('DEBT', 'GOVERNMENT_SECURITY', 'Government Security', 33, 'INVESTMENT'),
    ('RETIREMENT', 'PPF', 'PPF', 41, 'INVESTMENT'),
    ('RETIREMENT', 'NPS', 'NPS', 42, 'INVESTMENT'),
    ('RETIREMENT', 'EPF', 'EPF', 43, 'INVESTMENT'),
    ('RETIREMENT', 'PENSION_PLAN', 'Pension Plan', 44, 'INVESTMENT'),
    -- Kept as a generic/legacy bucket for existing rows; prefer the finer categories below for new products.
    ('INSURANCE', 'LIFE_INSURANCE', 'Life Insurance', 51, 'INSURANCE_SAVINGS'),
    ('INSURANCE', 'ULIP', 'ULIP', 52, 'INSURANCE_SAVINGS'),
    ('INSURANCE', 'HEALTH_INSURANCE', 'Health Insurance', 53, 'PROTECTION_EXPENSE'),
    ('INSURANCE', 'LIC_MONEY_BACK', 'LIC Money Back', 54, 'INSURANCE_SAVINGS'),
    ('INSURANCE', 'ENDOWMENT', 'Endowment', 55, 'INSURANCE_SAVINGS'),
    ('INSURANCE', 'TERM_INSURANCE', 'Term Insurance', 56, 'PROTECTION_EXPENSE'),
    ('INSURANCE', 'RETURN_OF_PREMIUM_TERM', 'Return of Premium Term Insurance', 57, 'INSURANCE_SAVINGS'),
    ('COMMODITY', 'GOLD', 'Gold', 61, 'INVESTMENT'),
    ('COMMODITY', 'SILVER', 'Silver', 62, 'INVESTMENT'),
    ('COMMODITY', 'COMMODITY_FUND', 'Commodity Fund', 63, 'INVESTMENT'),
    ('REAL_ESTATE', 'PROPERTY', 'Property', 71, 'INVESTMENT'),
    ('REAL_ESTATE', 'REIT', 'REIT', 72, 'INVESTMENT'),
    ('REAL_ESTATE', 'LAND', 'Land', 73, 'INVESTMENT'),
    ('ALTERNATIVE', 'CRYPTO', 'Crypto', 81, 'INVESTMENT'),
    ('ALTERNATIVE', 'PRIVATE_EQUITY', 'Private Equity', 82, 'INVESTMENT'),
    ('ALTERNATIVE', 'COLLECTIBLE', 'Collectible', 83, 'INVESTMENT'),
    ('ALTERNATIVE', 'OTHER_ALTERNATIVE', 'Other Alternative', 84, 'INVESTMENT')
) AS child("parentCode", "code", "label", "sortOrder", "accountingTreatment")
JOIN public.app_meta_config_ref parent
  ON parent."module" = 'INVESTMENT'
 AND parent."configType" = 'ASSET_TYPE'
 AND parent."code" = child."parentCode"
ON CONFLICT ("code") DO UPDATE
SET
  "module" = EXCLUDED."module",
  "configType" = EXCLUDED."configType",
  "parentId" = EXCLUDED."parentId",
  "label" = EXCLUDED."label",
  "sortOrder" = EXCLUDED."sortOrder",
  "accountingTreatment" = EXCLUDED."accountingTreatment",
  "isActive" = true,
  "updatedAt" = now();

CREATE TABLE IF NOT EXISTS public.investment_asset_taxonomy (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "userId" INTEGER NOT NULL,
  "label" TEXT NOT NULL,
  "nodeType" TEXT NOT NULL,
  "level" INTEGER NOT NULL,
  "parentId" INTEGER NULL,
  "defaultAssetTypeMetaId" INTEGER NULL,
  "defaultAssetCategoryMetaId" INTEGER NULL,
  "sortOrder" INTEGER NOT NULL DEFAULT 0,
  "isActive" BOOLEAN NOT NULL DEFAULT true,
  "createdAt" TIMESTAMPTZ NOT NULL DEFAULT now(),
  "updatedAt" TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT "investment_asset_taxonomy_userId_fkey"
    FOREIGN KEY ("userId") REFERENCES public.users("id") ON DELETE CASCADE,
  CONSTRAINT "investment_asset_taxonomy_parentId_fkey"
    FOREIGN KEY ("parentId") REFERENCES public.investment_asset_taxonomy("id") ON DELETE SET NULL,
  CONSTRAINT "investment_asset_taxonomy_defaultAssetTypeMetaId_fkey"
    FOREIGN KEY ("defaultAssetTypeMetaId") REFERENCES public.app_meta_config_ref("id") ON DELETE SET NULL,
  CONSTRAINT "investment_asset_taxonomy_defaultAssetCategoryMetaId_fkey"
    FOREIGN KEY ("defaultAssetCategoryMetaId") REFERENCES public.app_meta_config_ref("id") ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS public.goals (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "userId" INTEGER NOT NULL,
  "categoryId" INTEGER NOT NULL,
  "name" TEXT NOT NULL,
  "description" TEXT NULL,
  "icon" TEXT NULL,
  "targetAmount" DOUBLE PRECISION NOT NULL,
  "currentAmount" DOUBLE PRECISION NOT NULL DEFAULT 0,
  "startDate" TIMESTAMPTZ NOT NULL DEFAULT now(),
  "deadline" TIMESTAMPTZ NULL,
  "categoryLabelSnapshot" TEXT NOT NULL,
  "createdAt" TIMESTAMPTZ NOT NULL DEFAULT now(),
  "updatedAt" TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT "goals_userId_fkey"
    FOREIGN KEY ("userId") REFERENCES public.users("id") ON DELETE CASCADE,
  CONSTRAINT "goals_categoryId_fkey"
    FOREIGN KEY ("categoryId") REFERENCES public.categories("id") ON DELETE RESTRICT
);

CREATE TABLE IF NOT EXISTS public.investments (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "userId" INTEGER NOT NULL,
  "accountId" INTEGER NULL,
  "assetTaxonomyId" INTEGER NULL,
  "assetTypeMetaId" INTEGER NOT NULL,
  "assetCategoryMetaId" INTEGER NOT NULL,
  "name" TEXT NOT NULL,
  "institutionName" TEXT NULL,
  "referenceNumber" TEXT NULL,
  "status" TEXT NOT NULL,
  "startDate" TIMESTAMPTZ NULL,
  "maturityDate" TIMESTAMPTZ NULL,
  "currency" TEXT NOT NULL,
  "totalInvested" DOUBLE PRECISION NOT NULL DEFAULT 0,
  "currentValue" DOUBLE PRECISION NOT NULL DEFAULT 0,
  "currentValueSource" TEXT NULL,
  "lastValuationAt" TIMESTAMPTZ NULL,
  "insuranceCover" DOUBLE PRECISION NULL,
  "contributionMode" public."InvestmentContributionMode" NOT NULL DEFAULT 'ONE_TIME',
  "accountingTreatmentOverride" public."AccountingTreatment" NULL,
  "notes" TEXT NULL,
  "createdAt" TIMESTAMPTZ NOT NULL DEFAULT now(),
  "updatedAt" TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT "investments_status_check"
    CHECK ("status" IN ('active', 'matured', 'closed')),

  CONSTRAINT "investments_userId_fkey"
    FOREIGN KEY ("userId") REFERENCES public.users("id") ON DELETE CASCADE,
  CONSTRAINT "investments_accountId_fkey"
    FOREIGN KEY ("accountId") REFERENCES public.financial_accounts("id") ON DELETE SET NULL,
  CONSTRAINT "investments_assetTaxonomyId_fkey"
    FOREIGN KEY ("assetTaxonomyId") REFERENCES public.investment_asset_taxonomy("id") ON DELETE SET NULL,
  CONSTRAINT "investments_assetTypeMetaId_fkey"
    FOREIGN KEY ("assetTypeMetaId") REFERENCES public.app_meta_config_ref("id") ON DELETE RESTRICT,
  CONSTRAINT "investments_assetCategoryMetaId_fkey"
    FOREIGN KEY ("assetCategoryMetaId") REFERENCES public.app_meta_config_ref("id") ON DELETE RESTRICT
);

CREATE TABLE IF NOT EXISTS public.investment_benefits (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "investmentId" INTEGER NOT NULL,
  "benefitType" public."InvestmentBenefitType" NOT NULL,
  "amount" DECIMAL(18,2) NOT NULL,
  "benefitDate" TIMESTAMPTZ NOT NULL,
  "status" public."InvestmentBenefitStatus" NOT NULL DEFAULT 'EXPECTED',
  "notes" TEXT NULL,
  "linkedEventId" INTEGER NULL,
  "createdAt" TIMESTAMPTZ NOT NULL DEFAULT now(),
  "updatedAt" TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT "investment_benefits_investmentId_fkey"
    FOREIGN KEY ("investmentId") REFERENCES public.investments("id") ON DELETE CASCADE,
  CONSTRAINT "investment_benefits_linkedEventId_fkey"
    FOREIGN KEY ("linkedEventId") REFERENCES public.investment_events("id") ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS public.transactions (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "userId" INTEGER NOT NULL,
  "categoryId" INTEGER NULL,
  "goalId" INTEGER NULL,
  "sourceAccountId" INTEGER NULL,
  "destinationAccountId" INTEGER NULL,
  "type" public."TransactionType" NOT NULL,
  "amount" DOUBLE PRECISION NOT NULL,
  "categoryLabelSnapshot" TEXT NULL,
  "date" TIMESTAMPTZ NOT NULL DEFAULT now(),
  "notes" TEXT NULL,
  "createdAt" TIMESTAMPTZ NOT NULL DEFAULT now(),
  "updatedAt" TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT "transactions_userId_fkey"
    FOREIGN KEY ("userId") REFERENCES public.users("id") ON DELETE CASCADE,
  CONSTRAINT "transactions_categoryId_fkey"
    FOREIGN KEY ("categoryId") REFERENCES public.categories("id") ON DELETE RESTRICT,
  CONSTRAINT "transactions_goalId_fkey"
    FOREIGN KEY ("goalId") REFERENCES public.goals("id") ON DELETE SET NULL,
  CONSTRAINT "transactions_sourceAccountId_fkey"
    FOREIGN KEY ("sourceAccountId") REFERENCES public.financial_accounts("id") ON DELETE SET NULL,
  CONSTRAINT "transactions_destinationAccountId_fkey"
    FOREIGN KEY ("destinationAccountId") REFERENCES public.financial_accounts("id") ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS public.investment_events (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "investmentId" INTEGER NOT NULL,
  "recurringPlanId" INTEGER NULL,
  "linkedTransactionId" INTEGER NULL,
  "eventType" public."InvestmentEventType" NOT NULL,
  "dueDate" TIMESTAMPTZ NULL,
  "status" public."InvestmentEventStatus" NOT NULL DEFAULT 'PENDING',
  "eventSource" public."InvestmentEventSource" NOT NULL DEFAULT 'MANUAL',
  "sequenceNumber" INTEGER NULL,
  "eventDate" TIMESTAMPTZ NOT NULL,
  "amount" DECIMAL(18,2) NULL,
  "units" DOUBLE PRECISION NULL,
  "pricePerUnit" DECIMAL(18,2) NULL,
  "netAmount" DECIMAL(18,2) NULL,
  "notes" TEXT NULL,
  "meta" JSONB NULL,
  "createdAt" TIMESTAMPTZ NOT NULL DEFAULT now(),
  "updatedAt" TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT "investment_events_investmentId_fkey"
    FOREIGN KEY ("investmentId") REFERENCES public.investments("id") ON DELETE CASCADE,
  CONSTRAINT "investment_events_recurringPlanId_fkey"
    FOREIGN KEY ("recurringPlanId") REFERENCES public.investment_contribution_plans("id") ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS public.investment_contribution_plans (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "investmentId" INTEGER NOT NULL,
  "status" TEXT NOT NULL,
  "amount" DECIMAL(18,2) NOT NULL,
  "cadenceUnit" TEXT NOT NULL,
  "cadenceInterval" INTEGER NOT NULL,
  "historicalImportMode" public."HistoricalImportMode" NOT NULL DEFAULT 'TRACK_FROM_TODAY',
  "anchorDate" TIMESTAMPTZ NOT NULL,
  "lastGeneratedDueDate" TIMESTAMPTZ NULL,
  "nextDueDate" TIMESTAMPTZ NULL,
  "endDate" TIMESTAMPTZ NULL,
  "reminderDaysBefore" INTEGER NULL,
  "autoCreateEvent" BOOLEAN NOT NULL DEFAULT false,
  "notes" TEXT NULL,
  "createdAt" TIMESTAMPTZ NOT NULL DEFAULT now(),
  "updatedAt" TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT "investment_contribution_plans_investmentId_fkey"
    FOREIGN KEY ("investmentId") REFERENCES public.investments("id") ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS public.valuation_snapshots (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "userId" INTEGER NOT NULL,
  "investmentId" INTEGER NOT NULL,
  "snapshotDate" TIMESTAMPTZ NOT NULL,
  "marketValue" DOUBLE PRECISION NOT NULL,
  "units" DOUBLE PRECISION NULL,
  "price" DOUBLE PRECISION NULL,
  "source" TEXT NULL,
  "createdAt" TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT "valuation_snapshots_userId_fkey"
    FOREIGN KEY ("userId") REFERENCES public.users("id") ON DELETE CASCADE,
  CONSTRAINT "valuation_snapshots_investmentId_fkey"
    FOREIGN KEY ("investmentId") REFERENCES public.investments("id") ON DELETE CASCADE
);

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'investment_events_linkedTransactionId_fkey'
  ) THEN
    ALTER TABLE public.investment_events
      ADD CONSTRAINT "investment_events_linkedTransactionId_fkey"
      FOREIGN KEY ("linkedTransactionId") REFERENCES public.transactions("id") ON DELETE SET NULL;
  END IF;
END $$;

CREATE OR REPLACE FUNCTION public.validate_investment_meta_config_pair()
RETURNS trigger AS $$
DECLARE
  type_row public.app_meta_config_ref%ROWTYPE;
  category_row public.app_meta_config_ref%ROWTYPE;
BEGIN
  SELECT * INTO type_row
  FROM public.app_meta_config_ref
  WHERE "module" = 'INVESTMENT'
    AND "configType" = 'ASSET_TYPE'
    AND "id" = NEW."assetTypeMetaId"
    AND "isActive" = true;

  IF NOT FOUND THEN
    RAISE EXCEPTION 'Invalid investment assetTypeMetaId: %', NEW."assetTypeMetaId";
  END IF;

  SELECT * INTO category_row
  FROM public.app_meta_config_ref
  WHERE "module" = 'INVESTMENT'
    AND "configType" = 'ASSET_CATEGORY'
    AND "id" = NEW."assetCategoryMetaId"
    AND "isActive" = true;

  IF NOT FOUND THEN
    RAISE EXCEPTION 'Invalid investment assetCategoryMetaId: %', NEW."assetCategoryMetaId";
  END IF;

  IF category_row."parentId" IS DISTINCT FROM NEW."assetTypeMetaId" THEN
    RAISE EXCEPTION 'assetCategoryMetaId % is not valid for assetTypeMetaId %', NEW."assetCategoryMetaId", NEW."assetTypeMetaId";
  END IF;

  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_validate_investment_meta_config_pair ON public.investments;
CREATE TRIGGER trg_validate_investment_meta_config_pair
BEFORE INSERT OR UPDATE OF "assetTypeMetaId", "assetCategoryMetaId"
ON public.investments
FOR EACH ROW
EXECUTE FUNCTION public.validate_investment_meta_config_pair();

CREATE OR REPLACE FUNCTION public.validate_investment_taxonomy_defaults_meta()
RETURNS trigger AS $$
DECLARE
  type_row public.app_meta_config_ref%ROWTYPE;
  category_row public.app_meta_config_ref%ROWTYPE;
BEGIN
  IF NEW."defaultAssetTypeMetaId" IS NOT NULL THEN
    SELECT * INTO type_row
    FROM public.app_meta_config_ref
    WHERE "module" = 'INVESTMENT'
      AND "configType" = 'ASSET_TYPE'
      AND "id" = NEW."defaultAssetTypeMetaId"
      AND "isActive" = true;

    IF NOT FOUND THEN
      RAISE EXCEPTION 'Invalid taxonomy defaultAssetTypeMetaId: %', NEW."defaultAssetTypeMetaId";
    END IF;
  END IF;

  IF NEW."defaultAssetCategoryMetaId" IS NOT NULL THEN
    IF NEW."defaultAssetTypeMetaId" IS NULL THEN
      RAISE EXCEPTION 'defaultAssetTypeMetaId is required when defaultAssetCategoryMetaId is set';
    END IF;

    SELECT * INTO category_row
    FROM public.app_meta_config_ref
    WHERE "module" = 'INVESTMENT'
      AND "configType" = 'ASSET_CATEGORY'
      AND "id" = NEW."defaultAssetCategoryMetaId"
      AND "isActive" = true;

    IF NOT FOUND THEN
      RAISE EXCEPTION 'Invalid taxonomy defaultAssetCategoryMetaId: %', NEW."defaultAssetCategoryMetaId";
    END IF;

    IF category_row."parentId" IS DISTINCT FROM NEW."defaultAssetTypeMetaId" THEN
      RAISE EXCEPTION 'defaultAssetCategoryMetaId % is not valid for defaultAssetTypeMetaId %', NEW."defaultAssetCategoryMetaId", NEW."defaultAssetTypeMetaId";
    END IF;
  END IF;

  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_validate_investment_taxonomy_defaults_meta ON public.investment_asset_taxonomy;
CREATE TRIGGER trg_validate_investment_taxonomy_defaults_meta
BEFORE INSERT OR UPDATE OF "defaultAssetTypeMetaId", "defaultAssetCategoryMetaId"
ON public.investment_asset_taxonomy
FOR EACH ROW
EXECUTE FUNCTION public.validate_investment_taxonomy_defaults_meta();

-- Indexes aligned with Prisma model.
CREATE INDEX IF NOT EXISTS "app_meta_config_ref_module_configType_idx"
  ON public.app_meta_config_ref ("module", "configType");
CREATE INDEX IF NOT EXISTS "app_meta_config_ref_parentId_idx"
  ON public.app_meta_config_ref ("parentId");

CREATE INDEX IF NOT EXISTS "transactions_userId_idx" ON public.transactions ("userId");
CREATE INDEX IF NOT EXISTS "transactions_date_idx" ON public.transactions ("date");
CREATE INDEX IF NOT EXISTS "transactions_type_idx" ON public.transactions ("type");
CREATE INDEX IF NOT EXISTS "transactions_goalId_idx" ON public.transactions ("goalId");
CREATE INDEX IF NOT EXISTS "transactions_categoryId_idx" ON public.transactions ("categoryId");
CREATE INDEX IF NOT EXISTS "transactions_sourceAccountId_idx" ON public.transactions ("sourceAccountId");
CREATE INDEX IF NOT EXISTS "transactions_destinationAccountId_idx" ON public.transactions ("destinationAccountId");

CREATE INDEX IF NOT EXISTS "goals_userId_idx" ON public.goals ("userId");
CREATE INDEX IF NOT EXISTS "goals_categoryId_idx" ON public.goals ("categoryId");

CREATE INDEX IF NOT EXISTS "categories_userId_idx" ON public.categories ("userId");
CREATE INDEX IF NOT EXISTS "financial_accounts_userId_idx" ON public.financial_accounts ("userId");

CREATE INDEX IF NOT EXISTS "investments_userId_idx" ON public.investments ("userId");
CREATE INDEX IF NOT EXISTS "investments_accountId_idx" ON public.investments ("accountId");
CREATE INDEX IF NOT EXISTS "investments_assetTaxonomyId_idx" ON public.investments ("assetTaxonomyId");
CREATE INDEX IF NOT EXISTS "investments_assetTypeMetaId_idx" ON public.investments ("assetTypeMetaId");
CREATE INDEX IF NOT EXISTS "investments_assetCategoryMetaId_idx" ON public.investments ("assetCategoryMetaId");

CREATE INDEX IF NOT EXISTS "investment_asset_taxonomy_parentId_idx" ON public.investment_asset_taxonomy ("parentId");
CREATE INDEX IF NOT EXISTS "investment_asset_taxonomy_userId_idx" ON public.investment_asset_taxonomy ("userId");
CREATE INDEX IF NOT EXISTS "investment_asset_taxonomy_nodeType_idx" ON public.investment_asset_taxonomy ("nodeType");
CREATE INDEX IF NOT EXISTS "investment_asset_taxonomy_level_idx" ON public.investment_asset_taxonomy ("level");
CREATE INDEX IF NOT EXISTS "investment_asset_taxonomy_defaultAssetTypeMetaId_idx" ON public.investment_asset_taxonomy ("defaultAssetTypeMetaId");
CREATE INDEX IF NOT EXISTS "investment_asset_taxonomy_defaultAssetCategoryMetaId_idx" ON public.investment_asset_taxonomy ("defaultAssetCategoryMetaId");

CREATE INDEX IF NOT EXISTS "investment_events_investmentId_idx" ON public.investment_events ("investmentId");
CREATE INDEX IF NOT EXISTS "investment_events_recurringPlanId_idx" ON public.investment_events ("recurringPlanId");
CREATE INDEX IF NOT EXISTS "investment_events_dueDate_idx" ON public.investment_events ("dueDate");
CREATE INDEX IF NOT EXISTS "investment_events_status_idx" ON public.investment_events ("status");
CREATE UNIQUE INDEX IF NOT EXISTS "investment_events_linkedTransactionId_key"
  ON public.investment_events ("linkedTransactionId");
CREATE UNIQUE INDEX IF NOT EXISTS "investment_events_recurringPlanId_dueDate_eventType_key"
  ON public.investment_events ("recurringPlanId", "dueDate", "eventType");

CREATE INDEX IF NOT EXISTS "investment_contribution_plans_investmentId_idx" ON public.investment_contribution_plans ("investmentId");
CREATE INDEX IF NOT EXISTS "investment_contribution_plans_status_idx" ON public.investment_contribution_plans ("status");
CREATE INDEX IF NOT EXISTS "investment_contribution_plans_nextDueDate_idx" ON public.investment_contribution_plans ("nextDueDate");

CREATE INDEX IF NOT EXISTS "valuation_snapshots_userId_idx" ON public.valuation_snapshots ("userId");
CREATE INDEX IF NOT EXISTS "valuation_snapshots_investmentId_idx" ON public.valuation_snapshots ("investmentId");
CREATE INDEX IF NOT EXISTS "valuation_snapshots_snapshotDate_idx" ON public.valuation_snapshots ("snapshotDate");

CREATE INDEX IF NOT EXISTS "investment_benefits_investmentId_idx" ON public.investment_benefits ("investmentId");
CREATE INDEX IF NOT EXISTS "investment_benefits_status_idx" ON public.investment_benefits ("status");
CREATE INDEX IF NOT EXISTS "investment_benefits_benefitDate_idx" ON public.investment_benefits ("benefitDate");

COMMIT;
